/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvegarde;


import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.*;
import outils.*;

/**
 *
 * @author andre
 */
public class Main_sav_01 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main_sav_01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJeux = new javax.swing.ButtonGroup();
        buttonGroupAdherents = new javax.swing.ButtonGroup();
        jPanelMenu = new javax.swing.JPanel();
        jButtonSortie = new javax.swing.JButton();
        jButtonEntree = new javax.swing.JButton();
        jButtonJeux = new javax.swing.JButton();
        jButtonAdherent = new javax.swing.JButton();
        jButtonReservation = new javax.swing.JButton();
        jButtonAnimation = new javax.swing.JButton();
        jButtonStatBilan = new javax.swing.JButton();
        jPanelJeux = new javax.swing.JPanel();
        jRadioButtonJeuxTous = new javax.swing.JRadioButton();
        jRadioButtonJeuxDispo = new javax.swing.JRadioButton();
        jRadioButtonJeuxSortis = new javax.swing.JRadioButton();
        jRadioButtonJeuxEmpPar = new javax.swing.JRadioButton();
        jRadioButtonJeuxSelect = new javax.swing.JRadioButton();
        jRadioButtonJeuxRechercher = new javax.swing.JRadioButton();
        jTextFieldRecherheJeux = new javax.swing.JTextField();
        jScrollPaneJeux = new javax.swing.JScrollPane();
        jTableJeux = new javax.swing.JTable();
        jLabelTousLesJeux = new javax.swing.JLabel();
        jLabelLesJeuxDispo = new javax.swing.JLabel();
        jLabelLesJeuxSortis = new javax.swing.JLabel();
        jLabelLesJeuxEmpPar = new javax.swing.JLabel();
        jLabelLesJeuxSelect = new javax.swing.JLabel();
        jPanelAdherent = new javax.swing.JPanel();
        jRadioButtonAdherentTous = new javax.swing.JRadioButton();
        jRadioButtonAdherentEmp = new javax.swing.JRadioButton();
        jRadioButtonAdherentRech = new javax.swing.JRadioButton();
        jRadioButtonAdherentAlertes = new javax.swing.JRadioButton();
        jTextFieldRechercheAdh = new javax.swing.JTextField();
        jLabelTousAdh = new javax.swing.JLabel();
        jScrollPaneAdh = new javax.swing.JScrollPane();
        jTableAdherent = new javax.swing.JTable();

        buttonGroupJeux.add(jRadioButtonJeuxTous);
        buttonGroupJeux.add(jRadioButtonJeuxSortis);
        buttonGroupJeux.add(jRadioButtonJeuxSelect);
        buttonGroupJeux.add(jRadioButtonJeuxRechercher);
        buttonGroupJeux.add(jRadioButtonJeuxEmpPar);
        buttonGroupJeux.add(jRadioButtonJeuxDispo);
        jRadioButtonJeuxTous.setSelected(true);

        buttonGroupAdherents.add(jRadioButtonAdherentTous);
        buttonGroupAdherents.add(jRadioButtonAdherentRech);
        buttonGroupAdherents.add(jRadioButtonAdherentEmp);
        buttonGroupAdherents.add(jRadioButtonAdherentAlertes);
        jRadioButtonAdherentTous.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Coffre A Jouer");
        setBackground(new java.awt.Color(153, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelMenu.setBackground(new java.awt.Color(199, 245, 233));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions principales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelMenu.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(1280, 70));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(1280, 70));

        jButtonSortie.setText("SORTIE");
        jButtonSortie.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortieActionPerformed(evt);
            }
        });

        jButtonEntree.setText("ENTREE");
        jButtonEntree.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntreeActionPerformed(evt);
            }
        });

        jButtonJeux.setBackground(new java.awt.Color(255, 51, 51));
        jButtonJeux.setForeground(new java.awt.Color(255, 51, 51));
        jButtonJeux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cubes_2.jpg"))); // NOI18N
        jButtonJeux.setText("NOUVEAUX JEUX");
        jButtonJeux.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonJeux.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonJeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJeuxActionPerformed(evt);
            }
        });

        jButtonAdherent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nouvel adhérent.jpg"))); // NOI18N
        jButtonAdherent.setText("NOUVEL ADHERENT");
        jButtonAdherent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAdherent.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdherentActionPerformed(evt);
            }
        });

        jButtonReservation.setText("RESERVATION");
        jButtonReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationActionPerformed(evt);
            }
        });

        jButtonAnimation.setText("ANIMATION");
        jButtonAnimation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimationActionPerformed(evt);
            }
        });

        jButtonStatBilan.setText("STATISTIQUE / BILAN");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStatBilan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReservation)
                        .addComponent(jButtonAnimation)
                        .addComponent(jButtonStatBilan))
                    .addComponent(jButtonAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelJeux.setBackground(new java.awt.Color(183, 228, 219));
        jPanelJeux.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les jeux", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelJeux.setMinimumSize(new java.awt.Dimension(1280, 375));
        jPanelJeux.setPreferredSize(new java.awt.Dimension(1280, 375));

        jRadioButtonJeuxTous.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxTous.setText("tous les jeux");

        jRadioButtonJeuxDispo.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxDispo.setText("les jeux disponibles");

        jRadioButtonJeuxSortis.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxSortis.setText("les jeux sortis");

        jRadioButtonJeuxEmpPar.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxEmpPar.setText("les jeux empruntés par");

        jRadioButtonJeuxSelect.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxSelect.setText("les jeux sélectionnés");

        jRadioButtonJeuxRechercher.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxRechercher.setText("RECHERCHER");

        jTableJeux.setModel(new ModelTableJeux());
        jTableJeux.setAutoResizeMode(jTableJeux.AUTO_RESIZE_OFF);
        jTableJeux.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableJeux.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableJeux.getColumnModel().getColumn(2).setPreferredWidth(300);
        jTableJeux.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTableJeux.getColumnModel().getColumn(4).setPreferredWidth(300);
        jTableJeux.getColumnModel().getColumn(5).setPreferredWidth(300);
        jScrollPaneJeux.setViewportView(jTableJeux);

        jLabelTousLesJeux.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxDispo.setText(" ");
        jLabelLesJeuxDispo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxSortis.setText(" ");
        jLabelLesJeuxSortis.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxEmpPar.setText(" ");
        jLabelLesJeuxEmpPar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxSelect.setText(" ");
        jLabelLesJeuxSelect.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelJeuxLayout = new javax.swing.GroupLayout(jPanelJeux);
        jPanelJeux.setLayout(jPanelJeuxLayout);
        jPanelJeuxLayout.setHorizontalGroup(
            jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneJeux)
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonJeuxDispo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonJeuxSortis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonJeuxTous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelLesJeuxSortis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLesJeuxDispo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jLabelTousLesJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(205, 205, 205)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJeuxEmpPar)
                            .addComponent(jRadioButtonJeuxSelect)
                            .addComponent(jRadioButtonJeuxRechercher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRecherheJeux)
                            .addComponent(jLabelLesJeuxSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLesJeuxEmpPar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelJeuxLayout.setVerticalGroup(
            jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                                .addComponent(jRadioButtonJeuxTous)
                                .addGap(1, 1, 1)
                                .addComponent(jRadioButtonJeuxDispo))
                            .addComponent(jLabelLesJeuxDispo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLesJeuxSortis, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonJeuxSortis)))
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTousLesJeux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonJeuxEmpPar)
                                .addComponent(jLabelLesJeuxEmpPar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJeuxSelect)
                            .addComponent(jLabelLesJeuxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonJeuxRechercher)
                            .addComponent(jTextFieldRecherheJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneJeux, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelJeuxLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButtonJeuxDispo, jRadioButtonJeuxEmpPar, jRadioButtonJeuxRechercher, jRadioButtonJeuxSelect, jRadioButtonJeuxSortis, jRadioButtonJeuxTous});

        jPanelAdherent.setBackground(new java.awt.Color(136, 191, 178));
        jPanelAdherent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les adhérents", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelAdherent.setMinimumSize(new java.awt.Dimension(1280, 375));
        jPanelAdherent.setPreferredSize(new java.awt.Dimension(1280, 375));

        jRadioButtonAdherentTous.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentTous.setText("tous les adhérents");

        jRadioButtonAdherentEmp.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentEmp.setText("les adhérents ayant empruntés un jeux");

        jRadioButtonAdherentRech.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentRech.setText("RECHERCHER");

        jRadioButtonAdherentAlertes.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentAlertes.setText("les alertes");

        jLabelTousAdh.setText(" ");
        jLabelTousAdh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableAdherent.setModel(new ModelTableAdherent());
        jTableAdherent.setAutoResizeMode(jTableAdherent.AUTO_RESIZE_OFF);
        jTableAdherent.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableAdherent.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableAdherent.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableAdherent.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableAdherent.getColumnModel().getColumn(4).setPreferredWidth(250);
        jTableAdherent.getColumnModel().getColumn(5).setPreferredWidth(250);
        jTableAdherent.getColumnModel().getColumn(6).setPreferredWidth(250);
        jTableAdherent.getColumnModel().getColumn(7).setPreferredWidth(250);
        jScrollPaneAdh.setViewportView(jTableAdherent);

        javax.swing.GroupLayout jPanelAdherentLayout = new javax.swing.GroupLayout(jPanelAdherent);
        jPanelAdherent.setLayout(jPanelAdherentLayout);
        jPanelAdherentLayout.setHorizontalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAdh)
                    .addGroup(jPanelAdherentLayout.createSequentialGroup()
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonAdherentEmp)
                            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAdherentTous)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTousAdh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(304, 304, 304)
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAdherentAlertes)
                            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAdherentRech)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldRechercheAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAdherentLayout.setVerticalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTousAdh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonAdherentTous)
                        .addComponent(jRadioButtonAdherentRech)
                        .addComponent(jTextFieldRechercheAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAdherentEmp)
                    .addComponent(jRadioButtonAdherentAlertes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAdh, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        final ImageButton button = new ImageButton(
            new ImageIcon("G:\\Java\\NetBeansProjects\\Projet\\src\\images\\cubes_2.jpg"));
        button.setLocation(1300,30);
        jPanelMenu.add(button);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSortieActionPerformed

    private void jButtonEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEntreeActionPerformed

    private void jButtonJeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJeuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJeuxActionPerformed

    private void jButtonAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdherentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdherentActionPerformed

    private void jButtonReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReservationActionPerformed

    private void jButtonAnimationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnimationActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        System.out.println("passage dans l'image bouton !!!");
    }     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Main_sav_01().setVisible(true);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAdherents;
    private javax.swing.ButtonGroup buttonGroupJeux;
    private javax.swing.JButton jButtonAdherent;
    private javax.swing.JButton jButtonAnimation;
    private javax.swing.JButton jButtonEntree;
    private javax.swing.JButton jButtonJeux;
    private javax.swing.JButton jButtonReservation;
    private javax.swing.JButton jButtonSortie;
    private javax.swing.JButton jButtonStatBilan;
    private javax.swing.JLabel jLabelLesJeuxDispo;
    private javax.swing.JLabel jLabelLesJeuxEmpPar;
    private javax.swing.JLabel jLabelLesJeuxSelect;
    private javax.swing.JLabel jLabelLesJeuxSortis;
    private javax.swing.JLabel jLabelTousAdh;
    private javax.swing.JLabel jLabelTousLesJeux;
    private javax.swing.JPanel jPanelAdherent;
    private javax.swing.JPanel jPanelJeux;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JRadioButton jRadioButtonAdherentAlertes;
    private javax.swing.JRadioButton jRadioButtonAdherentEmp;
    private javax.swing.JRadioButton jRadioButtonAdherentRech;
    private javax.swing.JRadioButton jRadioButtonAdherentTous;
    private javax.swing.JRadioButton jRadioButtonJeuxDispo;
    private javax.swing.JRadioButton jRadioButtonJeuxEmpPar;
    private javax.swing.JRadioButton jRadioButtonJeuxRechercher;
    private javax.swing.JRadioButton jRadioButtonJeuxSelect;
    private javax.swing.JRadioButton jRadioButtonJeuxSortis;
    private javax.swing.JRadioButton jRadioButtonJeuxTous;
    private javax.swing.JScrollPane jScrollPaneAdh;
    private javax.swing.JScrollPane jScrollPaneJeux;
    private javax.swing.JTable jTableAdherent;
    private javax.swing.JTable jTableJeux;
    private javax.swing.JTextField jTextFieldRechercheAdh;
    private javax.swing.JTextField jTextFieldRecherheJeux;
    // End of variables declaration//GEN-END:variables
}
