/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvegarde;

/**
 *
 * @author andre
 */
public class Main_Sav extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main_Sav() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJeux = new javax.swing.ButtonGroup();
        buttonGroupAdherents = new javax.swing.ButtonGroup();
        jPanelMenu = new javax.swing.JPanel();
        jButtonSortie = new javax.swing.JButton();
        jButtonEntree = new javax.swing.JButton();
        jButtonJeux = new javax.swing.JButton();
        jButtonAdherent = new javax.swing.JButton();
        jButtonReservation = new javax.swing.JButton();
        jButtonAnimation = new javax.swing.JButton();
        jPanelJeux = new javax.swing.JPanel();
        jRadioButtonJeuxTous = new javax.swing.JRadioButton();
        jRadioButtonJeuxDispo = new javax.swing.JRadioButton();
        jRadioButtonJeuxSortis = new javax.swing.JRadioButton();
        jRadioButtonJeuxEmpPar = new javax.swing.JRadioButton();
        jRadioButtonJeuxSelect = new javax.swing.JRadioButton();
        jRadioButtonJeuxRechercher = new javax.swing.JRadioButton();
        jTextFieldRecherheJeux = new javax.swing.JTextField();
        jScrollPaneJeux = new javax.swing.JScrollPane();
        jTableJeux = new javax.swing.JTable();
        jLabelTousLesJeux = new javax.swing.JLabel();
        jLabelLesJeuxDispo = new javax.swing.JLabel();
        jLabelLesJeuxSortis = new javax.swing.JLabel();
        jLabelLesJeuxEmpPar = new javax.swing.JLabel();
        jLabelLesJeuxSelect = new javax.swing.JLabel();
        jPanelAdherent = new javax.swing.JPanel();
        jRadioButtonAdherentTous = new javax.swing.JRadioButton();
        jRadioButtonAdherentEmp = new javax.swing.JRadioButton();
        jRadioButtonAdherentRech = new javax.swing.JRadioButton();
        jRadioButtonAdherentAlertes = new javax.swing.JRadioButton();
        jTextFieldRechercheAdh = new javax.swing.JTextField();
        jLabelTousAdh = new javax.swing.JLabel();
        jScrollPaneAdh = new javax.swing.JScrollPane();
        jTableAdherent = new javax.swing.JTable();

        buttonGroupJeux.add(jRadioButtonJeuxTous);
        buttonGroupJeux.add(jRadioButtonJeuxSortis);
        buttonGroupJeux.add(jRadioButtonJeuxSelect);
        buttonGroupJeux.add(jRadioButtonJeuxRechercher);
        buttonGroupJeux.add(jRadioButtonJeuxEmpPar);
        buttonGroupJeux.add(jRadioButtonJeuxDispo);
        jRadioButtonJeuxTous.setSelected(true);

        buttonGroupAdherents.add(jRadioButtonAdherentTous);
        buttonGroupAdherents.add(jRadioButtonAdherentRech);
        buttonGroupAdherents.add(jRadioButtonAdherentEmp);
        buttonGroupAdherents.add(jRadioButtonAdherentAlertes);
        jRadioButtonAdherentTous.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Coffre A Jouets");

        jPanelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions principales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelMenu.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(1280, 70));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(1280, 70));

        jButtonSortie.setText("SORTIE");
        jButtonSortie.setPreferredSize(new java.awt.Dimension(100, 25));

        jButtonEntree.setText("ENTREE");
        jButtonEntree.setPreferredSize(new java.awt.Dimension(100, 25));

        jButtonJeux.setText("NOUVEAUX JEUX");
        jButtonJeux.setPreferredSize(new java.awt.Dimension(100, 25));

        jButtonAdherent.setText("NOUVEL ADHERENT");
        jButtonAdherent.setPreferredSize(new java.awt.Dimension(100, 25));

        jButtonReservation.setText("RESERVATION");

        jButtonAnimation.setText("ANIMATION");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReservation)
                    .addComponent(jButtonAnimation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelJeux.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les jeux", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelJeux.setMinimumSize(new java.awt.Dimension(1280, 375));
        jPanelJeux.setPreferredSize(new java.awt.Dimension(1280, 375));

        jRadioButtonJeuxTous.setText("tous les jeux");
        jRadioButtonJeuxTous.setMaximumSize(new java.awt.Dimension(117, 23));
        jRadioButtonJeuxTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxTousActionPerformed(evt);
            }
        });

        jRadioButtonJeuxDispo.setText("les jeux disponibles");
        jRadioButtonJeuxDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxDispoActionPerformed(evt);
            }
        });

        jRadioButtonJeuxSortis.setText("les jeux sortis");

        jRadioButtonJeuxEmpPar.setText("les jeux empruntés par");

        jRadioButtonJeuxSelect.setText("les jeux sélectionés");

        jRadioButtonJeuxRechercher.setText("RECHERCHER");

        jScrollPaneJeux.setViewportView(jTableJeux);

        jLabelLesJeuxDispo.setText(" ");

        jLabelLesJeuxSortis.setText(" ");

        jLabelLesJeuxEmpPar.setText(" ");

        jLabelLesJeuxSelect.setText(" ");

        javax.swing.GroupLayout jPanelJeuxLayout = new javax.swing.GroupLayout(jPanelJeux);
        jPanelJeux.setLayout(jPanelJeuxLayout);
        jPanelJeuxLayout.setHorizontalGroup(
            jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneJeux)
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonJeuxDispo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonJeuxSortis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonJeuxTous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTousLesJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLesJeuxDispo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLesJeuxSortis, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGap(258, 258, 258)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJeuxEmpPar)
                            .addComponent(jRadioButtonJeuxSelect)
                            .addComponent(jRadioButtonJeuxRechercher))
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelLesJeuxEmpPar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jLabelLesJeuxSelect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRecherheJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelJeuxLayout.setVerticalGroup(
            jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTousLesJeux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonJeuxEmpPar)
                                .addComponent(jLabelLesJeuxEmpPar)))
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonJeuxSelect)
                            .addComponent(jLabelLesJeuxSelect)))
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addComponent(jRadioButtonJeuxTous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLesJeuxDispo)
                            .addComponent(jRadioButtonJeuxDispo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonJeuxRechercher)
                        .addComponent(jTextFieldRecherheJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelLesJeuxSortis))
                    .addComponent(jRadioButtonJeuxSortis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneJeux, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelAdherent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les adhérents", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelAdherent.setMinimumSize(new java.awt.Dimension(1280, 375));
        jPanelAdherent.setPreferredSize(new java.awt.Dimension(1280, 375));

        jRadioButtonAdherentTous.setText("tous les adhérents");

        jRadioButtonAdherentEmp.setText("les adhérents ayant empruntés un jeux");

        jRadioButtonAdherentRech.setText("RECHERCHER");

        jRadioButtonAdherentAlertes.setText("les alertes");

        jLabelTousAdh.setText(" ");

        jScrollPaneAdh.setViewportView(jTableAdherent);

        javax.swing.GroupLayout jPanelAdherentLayout = new javax.swing.GroupLayout(jPanelAdherent);
        jPanelAdherent.setLayout(jPanelAdherentLayout);
        jPanelAdherentLayout.setHorizontalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAdh)
                    .addGroup(jPanelAdherentLayout.createSequentialGroup()
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAdherentEmp)
                            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAdherentTous)
                                .addGap(32, 32, 32)
                                .addComponent(jLabelTousAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(258, 258, 258)
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAdherentAlertes)
                            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAdherentRech)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldRechercheAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(462, Short.MAX_VALUE))))
        );
        jPanelAdherentLayout.setVerticalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAdherentTous)
                    .addComponent(jRadioButtonAdherentRech)
                    .addComponent(jTextFieldRechercheAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTousAdh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAdherentEmp)
                    .addComponent(jRadioButtonAdherentAlertes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAdh, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelJeux, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonJeuxDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonJeuxDispoActionPerformed

    private void jRadioButtonJeuxTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxTousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonJeuxTousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Main_Sav().setVisible(true);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAdherents;
    private javax.swing.ButtonGroup buttonGroupJeux;
    private javax.swing.JButton jButtonAdherent;
    private javax.swing.JButton jButtonAnimation;
    private javax.swing.JButton jButtonEntree;
    private javax.swing.JButton jButtonJeux;
    private javax.swing.JButton jButtonReservation;
    private javax.swing.JButton jButtonSortie;
    private javax.swing.JLabel jLabelLesJeuxDispo;
    private javax.swing.JLabel jLabelLesJeuxEmpPar;
    private javax.swing.JLabel jLabelLesJeuxSelect;
    private javax.swing.JLabel jLabelLesJeuxSortis;
    private javax.swing.JLabel jLabelTousAdh;
    private javax.swing.JLabel jLabelTousLesJeux;
    private javax.swing.JPanel jPanelAdherent;
    private javax.swing.JPanel jPanelJeux;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JRadioButton jRadioButtonAdherentAlertes;
    private javax.swing.JRadioButton jRadioButtonAdherentEmp;
    private javax.swing.JRadioButton jRadioButtonAdherentRech;
    private javax.swing.JRadioButton jRadioButtonAdherentTous;
    private javax.swing.JRadioButton jRadioButtonJeuxDispo;
    private javax.swing.JRadioButton jRadioButtonJeuxEmpPar;
    private javax.swing.JRadioButton jRadioButtonJeuxRechercher;
    private javax.swing.JRadioButton jRadioButtonJeuxSelect;
    private javax.swing.JRadioButton jRadioButtonJeuxSortis;
    private javax.swing.JRadioButton jRadioButtonJeuxTous;
    private javax.swing.JScrollPane jScrollPaneAdh;
    private javax.swing.JScrollPane jScrollPaneJeux;
    private javax.swing.JTable jTableAdherent;
    private javax.swing.JTable jTableJeux;
    private javax.swing.JTextField jTextFieldRechercheAdh;
    private javax.swing.JTextField jTextFieldRecherheJeux;
    // End of variables declaration//GEN-END:variables
}
