/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poubelle;

import javax.swing.JFrame;

/**
 *
 *
 */
public class Adherent extends javax.swing.JFrame {

    private static boolean enab;
    private static Integer act;
    public boolean ferme;
  
    public static Adherent adherent;

    /**
     * Creates new form Jeux
     */
    public Adherent() {
        initComponents();
        jTextFieldReferenceAdherent.setText(reference);
    }

    /**
     * @param args the command line arguments
     */
    public static void adherent(Integer action) {
        // 1 -- Création
        // 2 -- Affichage
        // 3 -- Modification
     
        act = action;
        if (action == 1) {
            enab = true;
            adherent.modifEnableAdherent();
        }
        if (action == 2) {
            enab = false;
            adherent.modifEnableAdherent();
        }
        if (action == 3) {
            enab = true;
            adherent.modifEnableAdherent();
        }
        adherent.setVisible(true);
    }

    public static Adherent getInstance(Integer action , String ref, JFrame mere) {
        reference = ref;
        frame = mere;
        if (adherent == null) {
            adherent = new Adherent();
        }
        mere.setEnabled(false);
        adherent(action);
        adherent.jTextFieldReferenceAdherent.setText(ref);
        return adherent;
    }

    private void modifEnableAdherent() {

        jRadioButtonEcole.setEnabled(enab);
        jRadioButtonAssociation.setEnabled(enab);
        jRadioButtonFamille.setEnabled(enab);
        jRadioButtonRAM.setEnabled(enab);
        jTextFieldNomAdherent.setEnabled(enab);
        jTextFieldPrenomAdherent.setEnabled(enab);
        jTextAreaAdresse.setEnabled(enab);
        jTextFieldCodePostal.setEnabled(enab);
        jComboBoxVille.setEnabled(enab);
        jTextFieldTelephoneDomicile.setEnabled(enab);
        jTextFieldTelephonePortable.setEnabled(enab);
        jTextFieldTelephoneTravail.setEnabled(enab);
        jTablePersonnes.setEnabled(enab);
        jTextAreaNotes.setEnabled(enab);

        if (enab) {
            /**
             * Enable = True --> Création ou modification Enable = False -->
             * Affichage
             *
             */
            jButtonOK.setText("OK");
            jButtonAnnuler.setText("Annuler");
            ferme = false;

        } else {
            jButtonOK.setText("Modif");
            jButtonAnnuler.setText("Fermer");
            ferme = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTitre = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jPanellAdherent = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelRefAdherent = new javax.swing.JLabel();
        jTextFieldReferenceAdherent = new javax.swing.JTextField();
        jLabelTitreAdherent = new javax.swing.JLabel();
        jLabelNomAdherent = new javax.swing.JLabel();
        jTextFieldNomAdherent = new javax.swing.JTextField();
        jLabelPrenomAdherent = new javax.swing.JLabel();
        jTextFieldPrenomAdherent = new javax.swing.JTextField();
        jRadioButtonFamille = new javax.swing.JRadioButton();
        jRadioButtonAssociation = new javax.swing.JRadioButton();
        jRadioButtonRAM = new javax.swing.JRadioButton();
        jRadioButtonEcole = new javax.swing.JRadioButton();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelCodePostal = new javax.swing.JLabel();
        jTextFieldCodePostal = new javax.swing.JTextField();
        jLabelVille = new javax.swing.JLabel();
        jComboBoxVille = new javax.swing.JComboBox();
        jLabelTelephone = new javax.swing.JLabel();
        jTextFieldTelephonePortable = new javax.swing.JTextField();
        jLabelTelephonePortable = new javax.swing.JLabel();
        jLabelTelephoneDomicile = new javax.swing.JLabel();
        jLabelTelephoneTravail = new javax.swing.JLabel();
        jTextFieldTelephoneDomicile = new javax.swing.JTextField();
        jTextFieldTelephoneTravail = new javax.swing.JTextField();
        jScrollPaneAdresse = new javax.swing.JScrollPane();
        jTextAreaAdresse = new javax.swing.JTextArea();
        jScrollPaneNotes = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jLabelNotes = new javax.swing.JLabel();
        jLabelEcheanceCotisation = new javax.swing.JLabel();
        jTextFieldEcheanceCotisation = new javax.swing.JTextField();
        jLabelCredits = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonHistorique = new javax.swing.JButton();
        jScrollPanePersonnes = new javax.swing.JScrollPane();
        jTablePersonnes = new javax.swing.JTable();

        buttonGroupTitre.add(jRadioButtonFamille);
        buttonGroupTitre.add(jRadioButtonAssociation);
        buttonGroupTitre.add(jRadioButtonRAM);
        buttonGroupTitre.add(jRadioButtonEcole);
        jRadioButtonFamille.setSelected(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setTitle("ADHERENT");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanellAdherent.setBackground(new java.awt.Color(199, 245, 233));
        jPanellAdherent.setName(""); // NOI18N
        jPanellAdherent.setPreferredSize(new java.awt.Dimension(646, 825));

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTitre.setText("Fiche Adhérent");

        jLabelRefAdherent.setText("Référence");

        jTextFieldReferenceAdherent.setEnabled(false);
        jTextFieldReferenceAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReferenceAdherentActionPerformed(evt);
            }
        });

        jLabelTitreAdherent.setText("Titre");

        jLabelNomAdherent.setText("Nom");

        jLabelPrenomAdherent.setText("Prénom");

        jTextFieldPrenomAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomAdherentActionPerformed(evt);
            }
        });

        jRadioButtonFamille.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonFamille.setText("Famille");
        jRadioButtonFamille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFamilleMouseClicked(evt);
            }
        });
        jRadioButtonFamille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFamilleActionPerformed(evt);
            }
        });

        jRadioButtonAssociation.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonAssociation.setText("Association");

        jRadioButtonRAM.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonRAM.setText("RAM / Périscolaire");

        jRadioButtonEcole.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonEcole.setText("Ecole");

        jLabelAdresse.setText("Adresse");

        jLabelCodePostal.setText("Code postal");

        jLabelVille.setText("Ville ");

        jComboBoxVille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelTelephone.setText("Téléphone");

        jLabelTelephonePortable.setText("Portable");

        jLabelTelephoneDomicile.setText("Domicile");

        jLabelTelephoneTravail.setText("Travail");

        jTextFieldTelephoneDomicile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelephoneDomicileActionPerformed(evt);
            }
        });

        jTextFieldTelephoneTravail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelephoneTravailActionPerformed(evt);
            }
        });

        jTextAreaAdresse.setColumns(20);
        jTextAreaAdresse.setRows(5);
        jScrollPaneAdresse.setViewportView(jTextAreaAdresse);

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setRows(5);
        jScrollPaneNotes.setViewportView(jTextAreaNotes);

        jLabelNotes.setText("Notes");

        jLabelEcheanceCotisation.setText("Echéance cotis.");

        jTextFieldEcheanceCotisation.setText("12/12/2015");
        jTextFieldEcheanceCotisation.setEnabled(false);

        jLabelCredits.setText("CREDITS");

        jTextField1.setText("24 points");
        jTextField1.setEnabled(false);

        jButtonOK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonSupprimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSupprimer.setForeground(new java.awt.Color(255, 0, 51));
        jButtonSupprimer.setText("X");

        jButtonAnnuler.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnnulerMouseClicked(evt);
            }
        });
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jButtonHistorique.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonHistorique.setText(".../...");
        jButtonHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoriqueActionPerformed(evt);
            }
        });

        jTablePersonnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Membre", "Date de naissance"
            }
        ));
        jTablePersonnes.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePersonnes.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTablePersonnes.setRequestFocusEnabled(false);
        jTablePersonnes.getTableHeader().setReorderingAllowed(false);
        jScrollPanePersonnes.setViewportView(jTablePersonnes);

        javax.swing.GroupLayout jPanellAdherentLayout = new javax.swing.GroupLayout(jPanellAdherent);
        jPanellAdherent.setLayout(jPanellAdherentLayout);
        jPanellAdherentLayout.setHorizontalGroup(
            jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellAdherentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(jButtonSupprimer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOK)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnnuler)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHistorique)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellAdherentLayout.createSequentialGroup()
                        .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                .addComponent(jLabelAdresse)
                                .addGap(11, 11, 11)))
                        .addGap(487, 487, 487))
                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                        .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                .addComponent(jLabelTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabelTelephonePortable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTelephonePortable, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(238, 238, 238)
                                .addComponent(jTextFieldTelephoneTravail, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelTitreAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRefAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                        .addComponent(jTextFieldNomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPrenomAdherent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPrenomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldReferenceAdherent, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonFamille, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                .addComponent(jLabelNotes)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneNotes)
                                .addGap(80, 80, 80))
                            .addComponent(jScrollPanePersonnes))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                        .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEcheanceCotisation)
                                    .addComponent(jLabelCredits))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEcheanceCotisation, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                .addComponent(jLabelCodePostal)
                                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jRadioButtonAssociation)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonRAM)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonEcole))
                                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jScrollPaneAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellAdherentLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelVille, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jComboBoxVille, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanellAdherentLayout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addComponent(jLabelTelephoneDomicile)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldTelephoneDomicile, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTelephoneTravail)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanellAdherentLayout.setVerticalGroup(
            jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addGap(44, 44, 44)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRefAdherent)
                    .addComponent(jTextFieldReferenceAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitreAdherent)
                    .addComponent(jRadioButtonFamille)
                    .addComponent(jRadioButtonAssociation)
                    .addComponent(jRadioButtonRAM)
                    .addComponent(jRadioButtonEcole))
                .addGap(18, 18, 18)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomAdherent)
                    .addComponent(jLabelPrenomAdherent)
                    .addComponent(jTextFieldPrenomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdresse)
                    .addComponent(jScrollPaneAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodePostal)
                        .addComponent(jTextFieldCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelVille)
                    .addComponent(jComboBoxVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelephonePortable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelephonePortable)
                    .addComponent(jLabelTelephone)
                    .addComponent(jLabelTelephoneDomicile)
                    .addComponent(jTextFieldTelephoneDomicile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelephoneTravail)
                    .addComponent(jTextFieldTelephoneTravail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPanePersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNotes)
                    .addComponent(jScrollPaneNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEcheanceCotisation)
                    .addComponent(jTextFieldEcheanceCotisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCredits))
                .addGap(27, 27, 27)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanellAdherent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanellAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelephoneDomicileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneDomicileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelephoneDomicileActionPerformed

    private void jTextFieldReferenceAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReferenceAdherentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReferenceAdherentActionPerformed

    private void jTextFieldTelephoneTravailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneTravailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelephoneTravailActionPerformed

    private void jButtonHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoriqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistoriqueActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:

        adherent.setVisible(false);
       frame.setEnabled(true);

    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnnulerMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonAnnulerMouseClicked

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:

        /**
         * Enable = True --> Création ou modification Valider la création ou la
         * modification Si tout se passe bien, on passe en affichage
         */
        if (enab) {
            act = 2;
            enab = false;
            modifEnableAdherent();
        } else {
            /**
             * Enable = False --> Affichage Demande de modification
             */
            enab = true;
            act = 3;
            modifEnableAdherent();

        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jTextFieldPrenomAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomAdherentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomAdherentActionPerformed

    private void jRadioButtonFamilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFamilleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFamilleMouseClicked

    private void jRadioButtonFamilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFamilleActionPerformed


    }//GEN-LAST:event_jRadioButtonFamilleActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private static JFrame frame;
    private static String reference;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTitre;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonHistorique;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxVille;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCodePostal;
    private javax.swing.JLabel jLabelCredits;
    private javax.swing.JLabel jLabelEcheanceCotisation;
    private javax.swing.JLabel jLabelNomAdherent;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JLabel jLabelPrenomAdherent;
    private javax.swing.JLabel jLabelRefAdherent;
    private javax.swing.JLabel jLabelTelephone;
    private javax.swing.JLabel jLabelTelephoneDomicile;
    private javax.swing.JLabel jLabelTelephonePortable;
    private javax.swing.JLabel jLabelTelephoneTravail;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelTitreAdherent;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPanel jPanellAdherent;
    private javax.swing.JRadioButton jRadioButtonAssociation;
    private javax.swing.JRadioButton jRadioButtonEcole;
    private javax.swing.JRadioButton jRadioButtonFamille;
    private javax.swing.JRadioButton jRadioButtonRAM;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneAdresse;
    private javax.swing.JScrollPane jScrollPaneNotes;
    private javax.swing.JScrollPane jScrollPanePersonnes;
    private javax.swing.JTable jTablePersonnes;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaAdresse;
    private javax.swing.JTextArea jTextAreaNotes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCodePostal;
    private javax.swing.JTextField jTextFieldEcheanceCotisation;
    private javax.swing.JTextField jTextFieldNomAdherent;
    private javax.swing.JTextField jTextFieldPrenomAdherent;
    private javax.swing.JTextField jTextFieldReferenceAdherent;
    private javax.swing.JTextField jTextFieldTelephoneDomicile;
    private javax.swing.JTextField jTextFieldTelephonePortable;
    private javax.swing.JTextField jTextFieldTelephoneTravail;
    // End of variables declaration//GEN-END:variables
}
