/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author andre
 */
public class AdherentChoix extends javax.swing.JFrame {

    /**
     * Creates new form Sortie
     */
    public AdherentChoix() {
        initComponents();
        this.setLocation(400, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAdherent = new javax.swing.JPanel();
        jLabelAdherent = new javax.swing.JLabel();
        jTextFieldRechercheAdherent = new javax.swing.JTextField();
        jScrollPaneList = new javax.swing.JScrollPane();
        jListListeJeux = new javax.swing.JList();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHOISISSEZ UIN ADHERENT");

        jPanelAdherent.setBackground(new java.awt.Color(199, 245, 233));

        jLabelAdherent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAdherent.setText("Entrez le nom de l'adhérent ");

        jTextFieldRechercheAdherent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jListListeJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListListeJeux.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneList.setViewportView(jListListeJeux);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdherentLayout = new javax.swing.GroupLayout(jPanelAdherent);
        jPanelAdherent.setLayout(jPanelAdherentLayout);
        jPanelAdherentLayout.setHorizontalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdherentLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAdherent)
                            .addComponent(jScrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(jTextFieldRechercheAdherent)))
                    .addGroup(jPanelAdherentLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonAnnuler)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelAdherentLayout.setVerticalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelAdherent)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRechercheAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonAnnuler))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SortieJeux.jeux();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void choix() {
        new AdherentChoix().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelAdherent;
    private javax.swing.JList jListListeJeux;
    private javax.swing.JPanel jPanelAdherent;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JTextField jTextFieldRechercheAdherent;
    // End of variables declaration//GEN-END:variables
}
