/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dao.AdhérentManager;
import dao.HistoriqueManager;
import static interfaces.Adherent.adherent;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import entitées.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import model.*;

/**
 *
 *
 */
public class HistoriqueAdherent extends javax.swing.JFrame {

    public static HistoriqueAdherent historiqueAdherent;
    private static JFrame frame;
    private String ref_adh;
    private AdhérentManager adh_manag;
    private Adhérent adherent;
    private String nomPrenomAdh;
    private Personne adhPersonne;
    private HistoriqueManager histo_manag;
    private Historique histo;
    List<Historique> listeHistoAdh = new ArrayList<>();

    /**
     * Creates new form Jeux
     *
     * @param refAdh
     */
    public HistoriqueAdherent(String refAdh) {
        ref_adh = refAdh;
        initComponents();
        adh_manag = new AdhérentManager();
        histo_manag = new HistoriqueManager();

        adherent = adh_manag.getAdhérent(ref_adh);

        nomPrenomAdh = adherent.getTitre().concat(" ");
        adhPersonne = adherent.getRéférent();

        String concat = nomPrenomAdh.concat(adhPersonne.getNom().concat(" ").concat(adhPersonne.getPrénom()));
        jTextFieldNomPrenomAdherent.setText(concat);
        jTextFieldReferenceAdherent.setText(ref_adh);
        Image icone = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("images/ludo.jpg"));
        this.setIconImage(icone);


    }

    public static HistoriqueAdherent getInstance(JFrame mere, String refAdh) {

        frame = mere;
        if (historiqueAdherent == null) {
            historiqueAdherent = new HistoriqueAdherent(refAdh);
        }
        historiqueAdherent.setVisible(true);

        frame.setEnabled(false);
        return historiqueAdherent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanellAdherent = new javax.swing.JPanel();
        jLabelRefAdherent = new javax.swing.JLabel();
        jTextFieldReferenceAdherent = new javax.swing.JTextField();
        jLabelNomAdherent = new javax.swing.JLabel();
        jTextFieldNomPrenomAdherent = new javax.swing.JTextField();
        jScrollPanePersonnes = new javax.swing.JScrollPane();
        jTableHistoAdherent = new javax.swing.JTable();
        jPanelTitreHistoriqueAdherent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFermer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setTitle("ADHERENT");
        setResizable(false);

        jPanellAdherent.setBackground(new java.awt.Color(199, 245, 233));
        jPanellAdherent.setName(""); // NOI18N
        jPanellAdherent.setPreferredSize(new java.awt.Dimension(646, 825));

        jLabelRefAdherent.setText("Référence");

        jTextFieldReferenceAdherent.setEnabled(false);
        jTextFieldReferenceAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReferenceAdherentActionPerformed(evt);
            }
        });

        jLabelNomAdherent.setText("Nom et Prénom");

        jTextFieldNomPrenomAdherent.setEnabled(false);

        jTableHistoAdherent.setModel(new ModelTableHistoriqueAdherent(ref_adh));
        jTableHistoAdherent.setRequestFocusEnabled(false);
        jTableHistoAdherent.getTableHeader().setReorderingAllowed(false);
        jScrollPanePersonnes.setViewportView(jTableHistoAdherent);

        jPanelTitreHistoriqueAdherent.setBackground(new java.awt.Color(199, 245, 233));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fiche Adhérent");

        javax.swing.GroupLayout jPanelTitreHistoriqueAdherentLayout = new javax.swing.GroupLayout(jPanelTitreHistoriqueAdherent);
        jPanelTitreHistoriqueAdherent.setLayout(jPanelTitreHistoriqueAdherentLayout);
        jPanelTitreHistoriqueAdherentLayout.setHorizontalGroup(
            jPanelTitreHistoriqueAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTitreHistoriqueAdherentLayout.setVerticalGroup(
            jPanelTitreHistoriqueAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Historique");

        javax.swing.GroupLayout jPanellAdherentLayout = new javax.swing.GroupLayout(jPanellAdherent);
        jPanellAdherent.setLayout(jPanellAdherentLayout);
        jPanellAdherentLayout.setHorizontalGroup(
            jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitreHistoriqueAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPanePersonnes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFermer)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelRefAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldReferenceAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabelNomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNomPrenomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanellAdherentLayout.setVerticalGroup(
            jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellAdherentLayout.createSequentialGroup()
                .addComponent(jPanelTitreHistoriqueAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanellAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRefAdherent)
                    .addComponent(jTextFieldReferenceAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomAdherent)
                    .addComponent(jTextFieldNomPrenomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPanePersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButtonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanellAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanellAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldReferenceAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReferenceAdherentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReferenceAdherentActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        historiqueAdherent.setVisible(false);

    }//GEN-LAST:event_jButtonFermerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNomAdherent;
    private javax.swing.JLabel jLabelRefAdherent;
    private javax.swing.JPanel jPanelTitreHistoriqueAdherent;
    private javax.swing.JPanel jPanellAdherent;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPanePersonnes;
    private javax.swing.JTable jTableHistoAdherent;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNomPrenomAdherent;
    private javax.swing.JTextField jTextFieldReferenceAdherent;
    // End of variables declaration//GEN-END:variables
}
