/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.ArrayList;
import javax.swing.JFrame;
import model.*;

/**
 *
 * @author andre
 */
public class JeuChoix extends javax.swing.JFrame {

    private static JeuChoix instance = null;
    
    /**
     * Creates new form Sortie
     */
    private JeuChoix() {
        initComponents();
        this.setLocation(400, 50);
        setVisible(true);
    }

    public static JeuChoix getInstance(JFrame mere,int origine , ArrayList list,String libAdherent) {
        frame = mere;
        orig = origine;
        liste = list;
        libAdh = libAdherent;
        if (instance == null) {
            instance = new JeuChoix();
        }
        instance.setVisible(true);
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSortie = new javax.swing.JPanel();
        jLabelNumeroJeu = new javax.swing.JLabel();
        jTextFieldRechercheJeux = new javax.swing.JTextField();
        jScrollPaneList = new javax.swing.JScrollPane();
        jListListeJeux = new javax.swing.JList();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setTitle("CHOISISSEZ UIN JEU");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelSortie.setBackground(new java.awt.Color(199, 245, 233));

        jLabelNumeroJeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroJeu.setText("Entrez le numéro de référence ou le nom du jeu ");

        jTextFieldRechercheJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jListListeJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPaneList.setViewportView(jListListeJeux);
        jListListeJeux.setModel(new ModelListJeuChoix());

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSortieLayout = new javax.swing.GroupLayout(jPanelSortie);
        jPanelSortie.setLayout(jPanelSortieLayout);
        jPanelSortieLayout.setHorizontalGroup(
            jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSortieLayout.createSequentialGroup()
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSortieLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNumeroJeu)
                            .addComponent(jScrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(jTextFieldRechercheJeux)))
                    .addGroup(jPanelSortieLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonAnnuler)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelSortieLayout.setVerticalGroup(
            jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSortieLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelNumeroJeu)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRechercheJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonAnnuler))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("orig " + orig);
        switch (orig){
            case 1: // venant du main
                frame.setEnabled(true);
                break;
            case 2: // venant de sortiechoix
                SortieChoix.getInstance(frame, liste, libAdh);
                break;
        }         
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        if (orig == 1){
           liste = new   ArrayList();
        }
        if (! jListListeJeux.isSelectionEmpty()){
            liste.add(jListListeJeux.getSelectedValue());
        }
        SortieChoix.getInstance(frame,liste,libAdh);
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

  
    private static JFrame frame;
    private static int orig;
    private static ArrayList liste;
    private static String libAdh;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelNumeroJeu;
    private javax.swing.JList jListListeJeux;
    private javax.swing.JPanel jPanelSortie;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JTextField jTextFieldRechercheJeux;
    // End of variables declaration//GEN-END:variables
}
