/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dao.*;
import entitées.*;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author andre
 */
public class Jeux extends javax.swing.JFrame {
    
    private static Jeux instance = null;

    /**
     * Creates new form Jeux
     */
    public Jeux() {
        initComponents();
        jPanelPile.setVisible(false);
        this.setLocation(400, 50);
        setVisible(true);      
     }

    public static Jeux getInstance(int j,String refJeu ,JFrame mere) {
        numEntree=j;
        mjTextFieldReferenceJeu = refJeu;
        frame = mere;
        if (instance == null) {
            instance = new Jeux();
        }
        instance.setVisible(true);
        frame.setEnabled(false);
        switch (numEntree){
            case 1:
                //Saisie jeux
                //Récupération reference jeux
                instance.jButtonOK.setText("Modif");
                instance.jButtonAnnuler.setText("Fermer");
                instance.zoneEnable(true);
                break;
            default:
                //Afficher jeux
                instance.zoneEnable(false);        
                instance.afficherJeux();
                instance.zoneMemorise();
             
        }        
        return instance;
    }    

    public void enregistrerJeux(){
        //ref_jeu, nom, fabriquant, prix_achat, date_achat, nb_joueurs_min, nb_joueurs_max, consomme_piles, contenu, commentaires, points, don,id_age_min, id_age_max, id_pile
        Jeu jeu = new Jeu();
        jeu.setRef_jeu("15/003");
        jeu.setNom(jTextFieldNomDuJeu.getText());
        jeu.setFabricant(jTextFieldFabricantJeu.getText());
        jeu.setPrix_achat(jTextFieldPrixAchat.getText().equals("")?0.00:Double.parseDouble(jTextFieldPrixAchat.getText()));
        jeu.setDate_achat(jXDatePickerDateAchat.getDate());
        jeu.setNb_joueurs_min(Integer.parseInt("0"+jTextFieldNbJoueurMin.getText()));
        jeu.setNb_joueurs_max(Integer.parseInt("0"+jTextFieldNbJoueurMax.getText()));
        if (jRadioButtonReservationOui.isSelected()){
            jeu.setConsomme_piles(true);
        }else{
            jeu.setConsomme_piles(false);
        }
        jeu.setContenu(jTextAreaContenu.getText());
        jeu.setCommentaires(jTextAreaCommentaire.getText());
        jeu.setPoints(Integer.parseInt(jTextFieldNbPoints.getText().toString()));
        //_don ?
        //jeu.setAge_min();
        //jeu.setAge_max();
        //jeu pile
        
        JeuManager jm = new JeuManager();
        jm.nouveauJeu(jeu);
    }
    public void afficherJeux(){
        Jeu jeu = new Jeu();
        JeuManager jm = new JeuManager();
        jeu = jm.getJeu(mjTextFieldReferenceJeu);
        jTextFieldReferenceJeu.setText(mjTextFieldReferenceJeu);
        jTextFieldNbPoints.setText(""+jeu.getPoints());
        jTextFieldNomDuJeu.setText(""+jeu.getNom());
        jTextFieldFabricantJeu.setText(""+jeu.getFabricant());
        jTextFieldAgeMin.setText(""+jeu.getAge_min().getNb());
        if ((""+jeu.getAge_min().getNb()).equals("ans")){
            jRadioButtonAgeMinAns.doClick();
        }else{
            jRadioButtonAgeMinMois.doClick();
        }
        if (jeu.getAge_max().getNb() != 0){
        jTextFieldAgeMax.setText(""+jeu.getAge_max().getNb());
            if ((""+jeu.getAge_max().getNb()).equals("ans")){
                jRadioButtonAgeMaxAns.doClick();
            }else{
                jRadioButtonAgeMaxMois.doClick();
            }
        }
        jTextFieldNbJoueurMin.setText(""+jeu.getNb_joueurs_min());
        if (jeu.getNb_joueurs_max() != 0){
            jTextFieldNbJoueurMax.setText(""+jeu.getNb_joueurs_max());
        }
        jTextAreaCommentaire.setText(jeu.getCommentaires());
        jTextAreaContenu.setText(jeu.getContenu());
        jXDatePickerDateAchat.setDate(jeu.getDate_achat());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPile = new javax.swing.ButtonGroup();
        buttonGroupReservation = new javax.swing.ButtonGroup();
        buttonGroupAgeMin = new javax.swing.ButtonGroup();
        buttonGroupAgeMax = new javax.swing.ButtonGroup();
        jPanelJeu = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelRefJeux = new javax.swing.JLabel();
        jLabeNbPoint = new javax.swing.JLabel();
        jLabelNomJeu = new javax.swing.JLabel();
        jLabelFabricant = new javax.swing.JLabel();
        jLabelAgeMin = new javax.swing.JLabel();
        jLabelAgeA = new javax.swing.JLabel();
        jLabelNbJoueur = new javax.swing.JLabel();
        jLabelPiles = new javax.swing.JLabel();
        jRadioButtonPileNon = new javax.swing.JRadioButton();
        jRadioButtonPileOui = new javax.swing.JRadioButton();
        jPanelPile = new javax.swing.JPanel();
        jLabelTypeDePile = new javax.swing.JLabel();
        jComboBoxTypePile = new javax.swing.JComboBox();
        jLabelNbPiles = new javax.swing.JLabel();
        jTextFieldNbPiles = new javax.swing.JTextField();
        jScrollPaneContenu = new javax.swing.JScrollPane();
        jTextAreaContenu = new javax.swing.JTextArea();
        jLabelContenuDetaille = new javax.swing.JLabel();
        jLabelCommentaire = new javax.swing.JLabel();
        jScrollPaneCommentaire = new javax.swing.JScrollPane();
        jTextAreaCommentaire = new javax.swing.JTextArea();
        jTextFieldNbPoints = new javax.swing.JTextField();
        jTextFieldNomDuJeu = new javax.swing.JTextField();
        jLabelDateAchat = new javax.swing.JLabel();
        jLabelPrixAchat = new javax.swing.JLabel();
        jTextFieldPrixAchat = new javax.swing.JTextField();
        jLabelReservationPossible = new javax.swing.JLabel();
        jRadioButtonReservationNon = new javax.swing.JRadioButton();
        jRadioButtonReservationOui = new javax.swing.JRadioButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonHistorique = new javax.swing.JButton();
        jTextFieldReferenceJeu = new javax.swing.JTextField();
        jTextFieldAgeMin = new javax.swing.JTextField();
        jRadioButtonAgeMinMois = new javax.swing.JRadioButton();
        jRadioButtonAgeMinAns = new javax.swing.JRadioButton();
        jTextFieldAgeMax = new javax.swing.JTextField();
        jRadioButtonAgeMaxMois = new javax.swing.JRadioButton();
        jRadioButtonAgeMaxAns = new javax.swing.JRadioButton();
        jTextFieldNbJoueurMin = new javax.swing.JTextField();
        jTextFieldNbJoueurMax = new javax.swing.JTextField();
        jLabelJoueurA = new javax.swing.JLabel();
        jLabelJoueurB = new javax.swing.JLabel();
        jTextFieldFabricantJeu = new javax.swing.JTextField();
        jXDatePickerDateAchat = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerDateCreation = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();

        buttonGroupPile.add(jRadioButtonPileNon);
        buttonGroupPile.add(jRadioButtonPileOui);
        jRadioButtonPileNon.setSelected(true);

        buttonGroupReservation.add(jRadioButtonReservationNon);
        buttonGroupReservation.add(jRadioButtonReservationOui);
        jRadioButtonReservationNon.setSelected(true);

        buttonGroupAgeMin.add(jRadioButtonAgeMinAns);
        buttonGroupAgeMin.add(jRadioButtonAgeMinMois);
        jRadioButtonAgeMinAns.setSelected(true);

        buttonGroupAgeMax.add(jRadioButtonAgeMaxAns);
        buttonGroupAgeMax.add(jRadioButtonAgeMaxMois);
        jRadioButtonAgeMaxAns.setSelected(true);

        setTitle("Jeux");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelJeu.setBackground(new java.awt.Color(199, 245, 233));
        jPanelJeu.setPreferredSize(new java.awt.Dimension(800, 940));

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTitre.setText("Fiche Jeu");

        jLabelRefJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRefJeux.setText("Référence du jeu :");

        jLabeNbPoint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabeNbPoint.setText("Nombre de points :");

        jLabelNomJeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomJeu.setText("Nom du jeu :");

        jLabelFabricant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFabricant.setText("Fabricant :");

        jLabelAgeMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAgeMin.setText("Age : A partir de :");

        jLabelAgeA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAgeA.setText("à");

        jLabelNbJoueur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNbJoueur.setText("Nombre de joueurs  de :");

        jLabelPiles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPiles.setText("Piles :");

        jRadioButtonPileNon.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonPileNon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonPileNon.setText("Non");

        jRadioButtonPileOui.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonPileOui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonPileOui.setText("Oui");
        jRadioButtonPileOui.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonPileOuiStateChanged(evt);
            }
        });

        jPanelPile.setBackground(new java.awt.Color(199, 245, 233));

        jLabelTypeDePile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTypeDePile.setText("Type de piles :");

        jComboBoxTypePile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTypePile.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelNbPiles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNbPiles.setText("Nombre de piles :");

        jTextFieldNbPiles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelPileLayout = new javax.swing.GroupLayout(jPanelPile);
        jPanelPile.setLayout(jPanelPileLayout);
        jPanelPileLayout.setHorizontalGroup(
            jPanelPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPileLayout.createSequentialGroup()
                        .addComponent(jLabelTypeDePile)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTypePile, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPileLayout.createSequentialGroup()
                        .addComponent(jLabelNbPiles)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNbPiles, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanelPileLayout.setVerticalGroup(
            jPanelPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTypeDePile)
                    .addComponent(jComboBoxTypePile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanelPileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbPiles)
                    .addComponent(jTextFieldNbPiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jTextAreaContenu.setColumns(20);
        jTextAreaContenu.setRows(5);
        jScrollPaneContenu.setViewportView(jTextAreaContenu);

        jLabelContenuDetaille.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContenuDetaille.setText("Contenu détaillé :");

        jLabelCommentaire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCommentaire.setText("Commentaire :");

        jTextAreaCommentaire.setColumns(20);
        jTextAreaCommentaire.setRows(5);
        jScrollPaneCommentaire.setViewportView(jTextAreaCommentaire);

        jTextFieldNbPoints.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNomDuJeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelDateAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDateAchat.setText("Date d'achat : ");

        jLabelPrixAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrixAchat.setText("Prix d'achat : ");

        jTextFieldPrixAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelReservationPossible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelReservationPossible.setText("Réservation possible : ");

        jRadioButtonReservationNon.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonReservationNon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonReservationNon.setText("Non");

        jRadioButtonReservationOui.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonReservationOui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonReservationOui.setText("Oui");

        jButtonSupprimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSupprimer.setForeground(new java.awt.Color(255, 0, 51));
        jButtonSupprimer.setText("X");

        jButtonOK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonAnnuler.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jButtonHistorique.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonHistorique.setText("../..");
        jButtonHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoriqueActionPerformed(evt);
            }
        });

        jTextFieldReferenceJeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldAgeMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jRadioButtonAgeMinMois.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonAgeMinMois.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAgeMinMois.setText("mois");

        jRadioButtonAgeMinAns.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonAgeMinAns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAgeMinAns.setText("ans");

        jTextFieldAgeMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jRadioButtonAgeMaxMois.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonAgeMaxMois.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAgeMaxMois.setText("mois");

        jRadioButtonAgeMaxAns.setBackground(new java.awt.Color(199, 245, 233));
        jRadioButtonAgeMaxAns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAgeMaxAns.setText("ans");

        jTextFieldNbJoueurMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNbJoueurMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelJoueurA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelJoueurA.setText("joueur(s) à");

        jLabelJoueurB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelJoueurB.setText("joueurs");

        jTextFieldFabricantJeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jXDatePickerDateAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jXDatePickerDateCreation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Création :");

        javax.swing.GroupLayout jPanelJeuLayout = new javax.swing.GroupLayout(jPanelJeu);
        jPanelJeu.setLayout(jPanelJeuLayout);
        jPanelJeuLayout.setHorizontalGroup(
            jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJeuLayout.createSequentialGroup()
                        .addComponent(jLabelReservationPossible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addComponent(jRadioButtonReservationNon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonReservationOui)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonSupprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAnnuler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJeuLayout.createSequentialGroup()
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneContenu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneCommentaire, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelPrixAchat)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addComponent(jLabelRefJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldReferenceJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addComponent(jLabeNbPoint)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNbPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDateAchat)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jXDatePickerDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXDatePickerDateAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelCommentaire)
                            .addComponent(jLabelContenuDetaille)
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                                        .addComponent(jLabelPiles)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonPileNon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonPileOui))
                                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                                        .addComponent(jLabelNbJoueur)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNbJoueurMin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelJoueurA))
                                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                                        .addComponent(jLabelAgeMin)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAgeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonAgeMinMois)
                                            .addComponent(jRadioButtonAgeMinAns))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelAgeA, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)))
                                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelPile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                                        .addComponent(jTextFieldAgeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonAgeMaxMois)
                                            .addComponent(jRadioButtonAgeMaxAns)))
                                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jTextFieldNbJoueurMax, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelJoueurB))))
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomJeu)
                                    .addComponent(jLabelFabricant))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomDuJeu, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFabricantJeu))))
                        .addContainerGap(29, Short.MAX_VALUE))))
            .addGroup(jPanelJeuLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJeuLayout.setVerticalGroup(
            jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRefJeux)
                    .addComponent(jLabeNbPoint)
                    .addComponent(jTextFieldNbPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReferenceJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomJeu)
                    .addComponent(jTextFieldNomDuJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabricant)
                    .addComponent(jTextFieldFabricantJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAgeMin)
                            .addComponent(jTextFieldAgeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAgeA)
                            .addComponent(jTextFieldAgeMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAgeMaxMois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonAgeMaxAns))
                            .addGroup(jPanelJeuLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAgeMinMois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonAgeMinAns)))))
                .addGap(49, 49, 49)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbJoueur)
                    .addComponent(jTextFieldNbJoueurMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNbJoueurMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJoueurA)
                    .addComponent(jLabelJoueurB))
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPiles)
                            .addComponent(jRadioButtonPileNon)
                            .addComponent(jRadioButtonPileOui)))
                    .addGroup(jPanelJeuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanelPile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabelContenuDetaille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneContenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCommentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrixAchat)
                    .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDateAchat)
                        .addComponent(jXDatePickerDateAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPrixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jXDatePickerDateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReservationPossible)
                    .addComponent(jRadioButtonReservationNon)
                    .addComponent(jRadioButtonReservationOui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJeu, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJeu, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonPileOuiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonPileOuiStateChanged
        // TODO add your handling code here:
        if (jRadioButtonPileOui.isSelected()){
            jPanelPile.setVisible(true);
        }else{
            jPanelPile.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButtonPileOuiStateChanged

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        if(jButtonOK.getText().equals("Modif")){
            enregistrerJeux();               
        }
        switch (numEntree){
            case 1:
                jButtonOK.setText("Modif");
                jButtonAnnuler.setText("Fermer");
                numEntree = 2;
                zoneEnable(true);
                break;
            case 2:
                jButtonOK.setText("OK");
                jButtonAnnuler.setText("Annuler");
                numEntree = 3;
                zoneEnable(false);
                break;
            default :
                jButtonOK.setText("Modif");
                jButtonAnnuler.setText("Fermer");
                numEntree = 2;
                zoneEnable(true);
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        if (jButtonAnnuler.getText().equals("Fermer")){
            setVisible(false);
            frame.setEnabled(true);
        }else{
            restaureZone(mjTextFieldReferenceJeu , mjTextFieldNomDuJeu , mjTextFieldNbPoints , mjXDatePickerDateAchat , mjTextFieldPrixAchat , mjTextFieldNbPiles , mjTextFieldAgeMin , mjRadioButtonAgeMinAns , mjTextFieldFabricantJeu, mjTextFieldAgeMax , mjRadioButtonAgeMaxAns , mjComboBoxTypePile , mjTextAreaCommentaire , mjTextAreaContenu , mjRadioButtonPileNon , mjRadioButtonReservationNon , mjTextFieldNbJoueurMin , mjTextFieldNbJoueurMax);
        }
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoriqueActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HistoriqueJeu.getInstance(mjTextFieldReferenceJeu);
    }//GEN-LAST:event_jButtonHistoriqueActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

   
    private void zoneEnable(boolean bool){
        jTextFieldReferenceJeu.setEnabled(false);
        jTextFieldNomDuJeu.setEnabled(bool);
        jTextFieldNbPoints.setEnabled(bool);
        jXDatePickerDateAchat.setEnabled(bool);
        jTextFieldPrixAchat.setEnabled(bool);
        jTextFieldNbPiles.setEnabled(bool);
        jRadioButtonAgeMinAns.setEnabled(bool);
        jRadioButtonAgeMinMois.setEnabled(bool);
        jTextFieldFabricantJeu.setEnabled(bool);
        jTextFieldAgeMax.setEnabled(bool);
        jTextFieldAgeMin.setEnabled(bool);
        jRadioButtonAgeMaxAns.setEnabled(bool);
        jRadioButtonAgeMaxMois.setEnabled(bool);
        jComboBoxTypePile.setEnabled(bool);
        jTextAreaCommentaire.setEnabled(bool);
        jTextAreaContenu.setEnabled(bool);  
        jRadioButtonPileNon.setEnabled(bool);
        jRadioButtonPileOui.setEnabled(bool);
        jRadioButtonReservationNon.setEnabled(bool);
        jRadioButtonReservationOui.setEnabled(bool); 
        jTextFieldNbJoueurMax.setEnabled(bool);
        jTextFieldNbJoueurMin.setEnabled(bool);
    }
    private void zoneMemorise(){
        mjTextFieldReferenceJeu = jTextFieldReferenceJeu.getText() ;
        mjTextFieldNomDuJeu = jTextFieldNomDuJeu.getText();
        mjTextFieldNbPoints = jTextFieldNbPoints.getText();
        mjXDatePickerDateAchat = jXDatePickerDateAchat.getDate()!=null?jXDatePickerDateAchat.getDate().toString():"";
        mjTextFieldPrixAchat = jTextFieldPrixAchat.getText();
        mjTextFieldNbPiles = jTextFieldNbPiles.getText();
        mjTextFieldAgeMin = jTextFieldAgeMin.getText();
        if (jRadioButtonAgeMinAns.isSelected()){
            mjRadioButtonAgeMinAns = 0;
        }else{
            mjRadioButtonAgeMinAns = 1;
        }        

        mjTextFieldFabricantJeu = jTextFieldFabricantJeu.getText();
        mjTextFieldAgeMax = jTextFieldAgeMax.getText();
        if (jRadioButtonAgeMaxAns.isSelected()){
            mjRadioButtonAgeMaxAns = 0;
        }else{
            mjRadioButtonAgeMaxAns = 1;
        }        

        mjComboBoxTypePile = jComboBoxTypePile.getSelectedIndex();
        mjTextAreaCommentaire = jTextAreaCommentaire.getText();
        mjTextAreaContenu = jTextAreaContenu.getText();
        if (jRadioButtonPileNon.isSelected()){
            mjRadioButtonPileNon = 0;
        }else{
            mjRadioButtonPileNon = 1;
        }
        if (jRadioButtonReservationNon.isSelected()){
            mjRadioButtonReservationNon = 0;
        }else{
            mjRadioButtonReservationNon = 1;
        }
    }    
    private void restaureZone(String mjTextFieldReferenceJeu , String mjTextFieldNomDuJeu , String mjTextFieldNbPoints , String mjXDatePickerDateAchat , String mjTextFieldPrixAchat , String mjTextFieldNbPiles , String mjTextFieldAgeMin , int mjRadioButtonAgeMinAns , String mjTextFieldFabricantJeu, String mjTextFieldAgeMax , int mjRadioButtonAgeMaxAns , int mjComboBoxTypePile , String mjTextAreaCommentaire , String mjTextAreaContenu , int mjRadioButtonPileNon , int mjRadioButtonReservationNon , String mjTextFieldNbJoueurMin , String mjTextFieldNbJoueurMax){
        jTextFieldReferenceJeu.setText(mjTextFieldReferenceJeu);
        jTextFieldNomDuJeu.setText(mjTextFieldNomDuJeu);
        jTextFieldNbPoints.setText(mjTextFieldNbPoints);
        DateFormat format = new SimpleDateFormat("yyyyMMdd");
        Date madate = null;
        try {
            madate = format.parse(mjXDatePickerDateAchat);
        } catch (ParseException ex) {
            Logger.getLogger(Jeux.class.getName()).log(Level.SEVERE, null, ex);
        }
        jXDatePickerDateAchat.setDate(madate);
        jTextFieldPrixAchat.setText(mjTextFieldPrixAchat);
        jTextFieldNbPiles.setText(mjTextFieldNbPiles);     
        jTextFieldAgeMin.setText(mjTextFieldAgeMin);
        if (mjRadioButtonAgeMinAns == 0){
            jRadioButtonAgeMinAns.doClick();
        }else{
            jRadioButtonAgeMinMois.doClick();
        }        
        jTextFieldFabricantJeu.setText(mjTextFieldFabricantJeu);
        jTextFieldAgeMax.setText(mjTextFieldAgeMax);
        if (mjRadioButtonAgeMaxAns == 0){
            jRadioButtonAgeMaxAns.doClick();
        }else{
            jRadioButtonAgeMaxMois.doClick();
        }
        jTextFieldNbJoueurMin.setText(mjTextFieldNbJoueurMin);
        jTextFieldNbJoueurMax.setText(mjTextFieldNbJoueurMax);
        jComboBoxTypePile.setSelectedIndex(mjComboBoxTypePile);
        jTextAreaCommentaire.setText(mjTextAreaCommentaire);
        jTextAreaContenu.setText(mjTextAreaContenu);
        if (mjRadioButtonPileNon == 0){
            jRadioButtonPileNon.doClick();
        }else{
            jRadioButtonPileOui.doClick();
        }
        if (mjRadioButtonReservationNon == 0){
            jRadioButtonReservationNon.doClick();
        }else{
            jRadioButtonReservationOui.doClick();
        }            
    }    

    // Main du programme

    
    //Variables declaration
    private static JFrame frame;
    private static boolean boole;
    private static int numEntree;
    private static String mjTextFieldReferenceJeu;
    private String mjTextFieldNomDuJeu;
    private String mjTextFieldNbPoints;
    private String mjXDatePickerDateAchat;
    private String mjTextFieldPrixAchat;
    private String mjTextFieldNbPiles;
    private String mjTextFieldAgeMin;
    private int mjRadioButtonAgeMinAns;
    private String mjTextFieldFabricantJeu;
    private String mjTextFieldAgeMax;
    private int mjRadioButtonAgeMaxAns;
    private int mjComboBoxTypePile;
    private String mjTextAreaCommentaire;
    private String mjTextAreaContenu;
    private int mjRadioButtonPileNon;
    private int mjRadioButtonReservationNon;  
    private String mjTextFieldNbJoueurMin;
    private String mjTextFieldNbJoueurMax;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAgeMax;
    private javax.swing.ButtonGroup buttonGroupAgeMin;
    private javax.swing.ButtonGroup buttonGroupPile;
    private javax.swing.ButtonGroup buttonGroupReservation;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonHistorique;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBoxTypePile;
    private javax.swing.JLabel jLabeNbPoint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgeA;
    private javax.swing.JLabel jLabelAgeMin;
    private javax.swing.JLabel jLabelCommentaire;
    private javax.swing.JLabel jLabelContenuDetaille;
    private javax.swing.JLabel jLabelDateAchat;
    private javax.swing.JLabel jLabelFabricant;
    private javax.swing.JLabel jLabelJoueurA;
    private javax.swing.JLabel jLabelJoueurB;
    private javax.swing.JLabel jLabelNbJoueur;
    private javax.swing.JLabel jLabelNbPiles;
    private javax.swing.JLabel jLabelNomJeu;
    private javax.swing.JLabel jLabelPiles;
    private javax.swing.JLabel jLabelPrixAchat;
    private javax.swing.JLabel jLabelRefJeux;
    private javax.swing.JLabel jLabelReservationPossible;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelTypeDePile;
    private javax.swing.JPanel jPanelJeu;
    private javax.swing.JPanel jPanelPile;
    private javax.swing.JRadioButton jRadioButtonAgeMaxAns;
    private javax.swing.JRadioButton jRadioButtonAgeMaxMois;
    private javax.swing.JRadioButton jRadioButtonAgeMinAns;
    private javax.swing.JRadioButton jRadioButtonAgeMinMois;
    private javax.swing.JRadioButton jRadioButtonPileNon;
    private javax.swing.JRadioButton jRadioButtonPileOui;
    private javax.swing.JRadioButton jRadioButtonReservationNon;
    private javax.swing.JRadioButton jRadioButtonReservationOui;
    private javax.swing.JScrollPane jScrollPaneCommentaire;
    private javax.swing.JScrollPane jScrollPaneContenu;
    private javax.swing.JTextArea jTextAreaCommentaire;
    private javax.swing.JTextArea jTextAreaContenu;
    private javax.swing.JTextField jTextFieldAgeMax;
    private javax.swing.JTextField jTextFieldAgeMin;
    private javax.swing.JTextField jTextFieldFabricantJeu;
    private javax.swing.JTextField jTextFieldNbJoueurMax;
    private javax.swing.JTextField jTextFieldNbJoueurMin;
    private javax.swing.JTextField jTextFieldNbPiles;
    private javax.swing.JTextField jTextFieldNbPoints;
    private javax.swing.JTextField jTextFieldNomDuJeu;
    private javax.swing.JTextField jTextFieldPrixAchat;
    private javax.swing.JTextField jTextFieldReferenceJeu;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerDateAchat;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerDateCreation;
    // End of variables declaration//GEN-END:variables
}
