/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author andre
 */
public class JeuxChoix extends javax.swing.JFrame {
public static String ecranOrigine;
    private static JeuxChoix instance = null;

    /**
     * Creates new form Sortie
     */
    private JeuxChoix() {
        initComponents();
        this.setLocation(400, 50);
        setVisible(true);
    }

    public static JeuxChoix getInstance(String origine) {
        ecranOrigine = origine;
// La fenêtre d'origine peut être :
        // MAIN : Bouton Sortie sur l'écran principal
        // SORTIE : Depuis le bouton "Sortir un autre jeu" de l'écran de Sortie des jeux
        // RETOUR : Depuis le bouton "Choisir un jeu" de l'écran de Retour des jeux
        // RESERVATION : Depuis le bouton "Ajouter jeu" de l'écran RéservationChoix
        if (instance == null) {
            instance = new JeuxChoix();
        }
        instance.setVisible(true);
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSortie = new javax.swing.JPanel();
        jLabelNumeroJeu = new javax.swing.JLabel();
        jTextFieldRechercheJeux = new javax.swing.JTextField();
        jScrollPaneList = new javax.swing.JScrollPane();
        jListListeJeux = new javax.swing.JList();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setTitle("CHOISISSEZ UIN JEU");
        setAlwaysOnTop(true);

        jPanelSortie.setBackground(new java.awt.Color(199, 245, 233));

        jLabelNumeroJeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroJeu.setText("Entrez le numéro de référence ou le nom du jeu ");

        jTextFieldRechercheJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jListListeJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListListeJeux.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneList.setViewportView(jListListeJeux);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSortieLayout = new javax.swing.GroupLayout(jPanelSortie);
        jPanelSortie.setLayout(jPanelSortieLayout);
        jPanelSortieLayout.setHorizontalGroup(
            jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSortieLayout.createSequentialGroup()
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSortieLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNumeroJeu)
                            .addComponent(jScrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(jTextFieldRechercheJeux)))
                    .addGroup(jPanelSortieLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonAnnuler)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelSortieLayout.setVerticalGroup(
            jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSortieLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelNumeroJeu)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRechercheJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneList, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonAnnuler))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        if (ecranOrigine.equals("SORTIE")){
            SortieJeux.jeux();
        }
        if (ecranOrigine.equals("MAIN")){
            SortieJeux.jeux();}
         if (ecranOrigine.equals("RETOUR")){
            RetourJeux.getInstance(this);}
          if (ecranOrigine.equals("RESERVATION")){
            Reservation.reservation(2);}
    }//GEN-LAST:event_jButtonOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelNumeroJeu;
    private javax.swing.JList jListListeJeux;
    private javax.swing.JPanel jPanelSortie;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JTextField jTextFieldRechercheJeux;
    // End of variables declaration//GEN-END:variables
}
