/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dao.*;
import entitées.Adhérent;
import entitées.Jeu;
import java.awt.*;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import model.*;


/**
 *
 * @author andre
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Image icone = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("images/ludo.jpg"));
        this.setIconImage(icone);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ModelTableAdherent mta = new ModelTableAdherent();
        jLabelTousAdh.setText(String.valueOf(mta.getRowCount()));
        ModelTableJeux mtj = new ModelTableJeux();
        jLabelTousLesJeux.setText(String.valueOf(mtj.getRowCount()));
        JeuManager jm = new JeuManager();
        jLabelLesJeuxSortis.setText(String.valueOf(jm.getNbJeuxSortis()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJeux = new javax.swing.ButtonGroup();
        buttonGroupAdherents = new javax.swing.ButtonGroup();
        jPanelMenu = new javax.swing.JPanel();
        jButtonSortie = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jButtonJeux = new javax.swing.JButton();
        jButtonAdherent = new javax.swing.JButton();
        jButtonReservation = new javax.swing.JButton();
        jButtonAnimation = new javax.swing.JButton();
        jButtonStatBilan = new javax.swing.JButton();
        jPanelJeux = new javax.swing.JPanel();
        jRadioButtonJeuxTous = new javax.swing.JRadioButton();
        jRadioButtonJeuxDispo = new javax.swing.JRadioButton();
        jRadioButtonJeuxSortis = new javax.swing.JRadioButton();
        jRadioButtonJeuxEmpPar = new javax.swing.JRadioButton();
        jRadioButtonJeuxSelect = new javax.swing.JRadioButton();
        jRadioButtonJeuxRechercher = new javax.swing.JRadioButton();
        jTextFieldRechercheJeux = new javax.swing.JTextField();
        jScrollPaneJeux = new javax.swing.JScrollPane();
        jTableJeux = new javax.swing.JTable();
        jLabelTousLesJeux = new javax.swing.JLabel();
        jLabelLesJeuxDispo = new javax.swing.JLabel();
        jLabelLesJeuxSortis = new javax.swing.JLabel();
        jLabelLesJeuxEmpPar = new javax.swing.JLabel();
        jLabelLesJeuxSelect = new javax.swing.JLabel();
        jPanelAdherent = new javax.swing.JPanel();
        jRadioButtonAdherentTous = new javax.swing.JRadioButton();
        jRadioButtonAdherentEmp = new javax.swing.JRadioButton();
        jRadioButtonAdherentRech = new javax.swing.JRadioButton();
        jRadioButtonAdherentAlertes = new javax.swing.JRadioButton();
        jTextFieldRechercheAdh = new javax.swing.JTextField();
        jLabelTousAdh = new javax.swing.JLabel();
        jScrollPaneAdh = new javax.swing.JScrollPane();
        jTableAdherent = new javax.swing.JTable();

        buttonGroupJeux.add(jRadioButtonJeuxTous);
        buttonGroupJeux.add(jRadioButtonJeuxSortis);
        buttonGroupJeux.add(jRadioButtonJeuxSelect);
        buttonGroupJeux.add(jRadioButtonJeuxRechercher);
        buttonGroupJeux.add(jRadioButtonJeuxEmpPar);
        buttonGroupJeux.add(jRadioButtonJeuxDispo);
        jRadioButtonJeuxTous.setSelected(true);

        buttonGroupAdherents.add(jRadioButtonAdherentTous);
        buttonGroupAdherents.add(jRadioButtonAdherentRech);
        buttonGroupAdherents.add(jRadioButtonAdherentEmp);
        buttonGroupAdherents.add(jRadioButtonAdherentAlertes);
        jRadioButtonAdherentTous.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Coffre A Jouer");
        setBackground(new java.awt.Color(153, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelMenu.setBackground(new java.awt.Color(199, 245, 233));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions principales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanelMenu.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(1280, 70));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(1280, 70));

        jButtonSortie.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSortie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSortie.setText("SORTIE");
        jButtonSortie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSortie.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortieActionPerformed(evt);
            }
        });

        jButtonRetour.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRetour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRetour.setForeground(new java.awt.Color(255, 51, 51));
        jButtonRetour.setText("RETOUR");
        jButtonRetour.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jButtonJeux.setBackground(new java.awt.Color(255, 51, 51));
        jButtonJeux.setForeground(new java.awt.Color(255, 51, 51));
        jButtonJeux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cubes_2.jpg"))); // NOI18N
        jButtonJeux.setText("NOUVEAUX JEUX");
        jButtonJeux.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonJeux.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonJeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJeuxActionPerformed(evt);
            }
        });

        jButtonAdherent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nouvel adhérent.jpg"))); // NOI18N
        jButtonAdherent.setText("NOUVEL ADHERENT");
        jButtonAdherent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAdherent.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdherentActionPerformed(evt);
            }
        });

        jButtonReservation.setText("RESERVATION");
        jButtonReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationActionPerformed(evt);
            }
        });

        jButtonAnimation.setText("ANIMATION");
        jButtonAnimation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimationActionPerformed(evt);
            }
        });

        jButtonStatBilan.setText("STATISTIQUE / BILAN");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButtonJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStatBilan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jButtonJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonReservation)
                                .addComponent(jButtonAnimation)
                                .addComponent(jButtonStatBilan))
                            .addComponent(jButtonAdherent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        jPanelJeux.setBackground(new java.awt.Color(183, 228, 219));
        jPanelJeux.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les jeux", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanelJeux.setMinimumSize(new java.awt.Dimension(1280, 375));
        jPanelJeux.setPreferredSize(new java.awt.Dimension(1280, 375));

        jRadioButtonJeuxTous.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxTous.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonJeuxTous.setText("tous les jeux");
        jRadioButtonJeuxTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxTousActionPerformed(evt);
            }
        });

        jRadioButtonJeuxDispo.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxDispo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonJeuxDispo.setText("les jeux disponibles");
        jRadioButtonJeuxDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxDispoActionPerformed(evt);
            }
        });

        jRadioButtonJeuxSortis.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxSortis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonJeuxSortis.setText("les jeux sortis");
        jRadioButtonJeuxSortis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxSortisActionPerformed(evt);
            }
        });

        jRadioButtonJeuxEmpPar.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxEmpPar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonJeuxEmpPar.setText("les jeux empruntés par");
        jRadioButtonJeuxEmpPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxEmpParActionPerformed(evt);
            }
        });

        jRadioButtonJeuxSelect.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonJeuxSelect.setText("les jeux sélectionnés");
        jRadioButtonJeuxSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxSelectActionPerformed(evt);
            }
        });

        jRadioButtonJeuxRechercher.setBackground(new java.awt.Color(183, 228, 219));
        jRadioButtonJeuxRechercher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonJeuxRechercher.setText("RECHERCHER");
        jRadioButtonJeuxRechercher.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonJeuxRechercherStateChanged(evt);
            }
        });
        jRadioButtonJeuxRechercher.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonJeuxRechercherItemStateChanged(evt);
            }
        });
        jRadioButtonJeuxRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJeuxRechercherActionPerformed(evt);
            }
        });

        jTextFieldRechercheJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRechercheJeux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRechercheJeuxKeyReleased(evt);
            }
        });

        jTableJeux.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableJeux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJeuxMouseClicked(evt);
            }
        });
        jScrollPaneJeux.setViewportView(jTableJeux);
        jTableJeux.setModel(new ModelTableJeux());

        jLabelTousLesJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTousLesJeux.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTousLesJeux.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxDispo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLesJeuxDispo.setText(" ");
        jLabelLesJeuxDispo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxSortis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLesJeuxSortis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLesJeuxSortis.setText(" ");
        jLabelLesJeuxSortis.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxEmpPar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLesJeuxEmpPar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLesJeuxEmpPar.setText(" ");
        jLabelLesJeuxEmpPar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLesJeuxSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLesJeuxSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLesJeuxSelect.setText(" ");
        jLabelLesJeuxSelect.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelJeuxLayout = new javax.swing.GroupLayout(jPanelJeux);
        jPanelJeux.setLayout(jPanelJeuxLayout);
        jPanelJeuxLayout.setHorizontalGroup(
            jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneJeux)
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonJeuxDispo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonJeuxSortis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonJeuxTous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelLesJeuxSortis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLesJeuxDispo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jLabelTousLesJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(205, 205, 205)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJeuxEmpPar)
                            .addComponent(jRadioButtonJeuxSelect)
                            .addComponent(jRadioButtonJeuxRechercher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRechercheJeux)
                            .addComponent(jLabelLesJeuxSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLesJeuxEmpPar, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelJeuxLayout.setVerticalGroup(
            jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJeuxLayout.createSequentialGroup()
                                .addComponent(jRadioButtonJeuxTous)
                                .addGap(1, 1, 1)
                                .addComponent(jRadioButtonJeuxDispo))
                            .addComponent(jLabelLesJeuxDispo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLesJeuxSortis, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonJeuxSortis)))
                    .addGroup(jPanelJeuxLayout.createSequentialGroup()
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTousLesJeux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonJeuxEmpPar)
                                .addComponent(jLabelLesJeuxEmpPar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonJeuxSelect)
                            .addComponent(jLabelLesJeuxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonJeuxRechercher)
                            .addComponent(jTextFieldRechercheJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneJeux, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelJeuxLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButtonJeuxDispo, jRadioButtonJeuxEmpPar, jRadioButtonJeuxRechercher, jRadioButtonJeuxSelect, jRadioButtonJeuxSortis, jRadioButtonJeuxTous});

        jTextFieldRechercheJeux.setToolTipText("Taper la chaine de caractère à rechercher...");

        jPanelAdherent.setBackground(new java.awt.Color(136, 191, 178));
        jPanelAdherent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Les adhérents", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanelAdherent.setMinimumSize(new java.awt.Dimension(1280, 375));
        jPanelAdherent.setPreferredSize(new java.awt.Dimension(1280, 375));

        jRadioButtonAdherentTous.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentTous.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAdherentTous.setText("tous les adhérents");

        jRadioButtonAdherentEmp.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAdherentEmp.setText("les adhérents ayant empruntés un jeux");

        jRadioButtonAdherentRech.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentRech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAdherentRech.setText("RECHERCHER");

        jRadioButtonAdherentAlertes.setBackground(new java.awt.Color(136, 191, 178));
        jRadioButtonAdherentAlertes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAdherentAlertes.setText("les alertes");

        jTextFieldRechercheAdh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRechercheAdh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRechercheAdhKeyReleased(evt);
            }
        });

        jLabelTousAdh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTousAdh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTousAdh.setText(" ");
        jLabelTousAdh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableAdherent.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableAdherent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdherentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableAdherentMousePressed(evt);
            }
        });
        jTableAdherent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAdherentKeyReleased(evt);
            }
        });
        jScrollPaneAdh.setViewportView(jTableAdherent);
        jTableAdherent.setModel(new ModelTableAdherent());

        javax.swing.GroupLayout jPanelAdherentLayout = new javax.swing.GroupLayout(jPanelAdherent);
        jPanelAdherent.setLayout(jPanelAdherentLayout);
        jPanelAdherentLayout.setHorizontalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAdh)
                    .addGroup(jPanelAdherentLayout.createSequentialGroup()
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonAdherentEmp)
                            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAdherentTous)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTousAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(304, 304, 304)
                        .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAdherentAlertes)
                            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                                .addComponent(jRadioButtonAdherentRech)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldRechercheAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 345, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAdherentLayout.setVerticalGroup(
            jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdherentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTousAdh)
                    .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonAdherentTous)
                        .addComponent(jRadioButtonAdherentRech)
                        .addComponent(jTextFieldRechercheAdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAdherentEmp)
                    .addComponent(jRadioButtonAdherentAlertes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAdh, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelJeux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortieActionPerformed
        // TODO add your handling code here:     
        if (jTableJeux.getSelectedRow() >=0 ){
            ArrayList listJeuxSelect = new ArrayList();
            int rows = jTableJeux.getRowCount();
            for (int i = 0; i < rows ; i++){
                if (jTableJeux.isRowSelected(i)){                          
                    listJeuxSelect.add(""+jTableJeux.getValueAt(i,1).toString() + "  "+jTableJeux.getValueAt(i,3).toString());
                }
            }
            SortieChoix.getInstance(this,listJeuxSelect,jLabelLesJeuxEmpPar.getText().toString());
        }else{
            System.out.println("selection non");
            JeuChoix.getInstance(this,1,null,null);
        }
    }//GEN-LAST:event_jButtonSortieActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
        RetourJeux.getInstance(this);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonJeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJeuxActionPerformed
        // TODO add your handling code here:     
        Jeux.getInstance(1,"",this);
    }//GEN-LAST:event_jButtonJeuxActionPerformed

    private void jButtonAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdherentActionPerformed
        // TODO add your handling code here:
        Adherent.getInstance(1,"");
    }//GEN-LAST:event_jButtonAdherentActionPerformed

    private void jButtonReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReservationActionPerformed

    private void jButtonAnimationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnimationActionPerformed

    private void jRadioButtonJeuxTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxTousActionPerformed
        // TODO add your handling code here:
        jTableJeux.setModel(new ModelTableJeux());
    }//GEN-LAST:event_jRadioButtonJeuxTousActionPerformed

    private void jRadioButtonJeuxDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxDispoActionPerformed
        // TODO add your handling code here:
        jTableJeux.setModel(new ModelTableJeux(true));
    }//GEN-LAST:event_jRadioButtonJeuxDispoActionPerformed

    private void jRadioButtonJeuxSortisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxSortisActionPerformed
        // TODO add your handling code here:
        jTableJeux.setModel(new ModelTableJeux(false));
    }//GEN-LAST:event_jRadioButtonJeuxSortisActionPerformed

    private void jRadioButtonJeuxSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxSelectActionPerformed
        // TODO add your handling code here:

        jLabelLesJeuxSelect.setText(""+jTableJeux.getSelectedRowCount());
        if (jRadioButtonJeuxSelect.isSelected()){
             ArrayList jeux = new ArrayList<>();
            for(int i = 0; i < jTableJeux.getRowCount(); i++) {
                if (jTableJeux.isRowSelected(i)){
                    Jeu j = ((ModelTableJeux)jTableJeux.getModel()).getListeJeu().get(i);
                    jeux.add(j);
                }
            }
            jTableJeux.removeAll();
            ModelTableJeux temp = new ModelTableJeux();
            temp.setListeJeu(jeux);
            jTableJeux.setModel(temp);
        
        }
    }//GEN-LAST:event_jRadioButtonJeuxSelectActionPerformed

    private void jRadioButtonJeuxRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxRechercherActionPerformed
        
        jTableJeux.setModel(new ModelTableJeux());
        jTextFieldRechercheJeux.setText("");
    }//GEN-LAST:event_jRadioButtonJeuxRechercherActionPerformed

    private void jTableAdherentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdherentMouseClicked
        
        if (jTableAdherent.getSelectedRow() >= 0){
            switch (evt.getClickCount()){
                case 1:
                    jLabelLesJeuxEmpPar.setText(jTableAdherent.getValueAt(jTableAdherent.getSelectedRow(),6).toString());
                    break;
                case 2:
                    //Adherent.getInstance(2,jTableAdherent.getValueAt(jTableAdherent.getSelectedRow(),1).toString());
                    Adherent.getInstance().setFenetre(2, jTableAdherent.getValueAt(jTableAdherent.getSelectedRow(),1).toString());
                    break;
            }
        }   
    }//GEN-LAST:event_jTableAdherentMouseClicked

    private void jTextFieldRechercheAdhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercheAdhKeyReleased
        // TODO add your handling code here:
        if (jRadioButtonAdherentRech.isSelected()){
            ModelTableAdherent myModel = new ModelTableAdherent();
            TableRowSorter sorter = new TableRowSorter(myModel);
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*"+ jTextFieldRechercheAdh.getText()+".*"));
            jTableAdherent.setRowSorter(sorter);
        }
    }//GEN-LAST:event_jTextFieldRechercheAdhKeyReleased

    private void jTextFieldRechercheJeuxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercheJeuxKeyReleased
        // TODO add your handling code here:
        if (jRadioButtonJeuxRechercher.isSelected()){
            ModelTableJeux myModel = new ModelTableJeux();
            TableRowSorter sorter = new TableRowSorter(myModel);
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*"+ jTextFieldRechercheJeux.getText()+".*"));
            jTableJeux.setRowSorter(sorter);
        }
    }//GEN-LAST:event_jTextFieldRechercheJeuxKeyReleased

    private void jTableJeuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJeuxMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            Jeux.getInstance(2,jTableJeux.getValueAt(jTableJeux.getSelectedRow(),1).toString(),this);
        }
        
    }//GEN-LAST:event_jTableJeuxMouseClicked

    private void jTableAdherentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdherentMousePressed
        // TODO add your handling code here:
        if (jTableAdherent.getSelectedRow() >= 0){
            jLabelLesJeuxEmpPar.setText(jTableAdherent.getValueAt(jTableAdherent.getSelectedRow(),6).toString());
        }else{
            jLabelLesJeuxEmpPar.setText("");
        }
    }//GEN-LAST:event_jTableAdherentMousePressed

    private void jTableAdherentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAdherentKeyReleased
        // TODO add your handling code here:
        if (jTableAdherent.getSelectedRow() >= 0){
            jLabelLesJeuxEmpPar.setText(jTableAdherent.getValueAt(jTableAdherent.getSelectedRow(),6).toString());
        }else{
            jLabelLesJeuxEmpPar.setText("");
        }
    }//GEN-LAST:event_jTableAdherentKeyReleased

    private void jRadioButtonJeuxEmpParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxEmpParActionPerformed
        // TODO add your handling code here:
        if (! jLabelLesJeuxEmpPar.getText().equals("") && ! jLabelLesJeuxEmpPar.getText().equals(" ")){
            Adhérent adh = new Adhérent();
            adh.setRef_adhérent(jLabelLesJeuxEmpPar.getText());
            jTableJeux.setModel(new ModelTableJeux(adh));
        }
    }//GEN-LAST:event_jRadioButtonJeuxEmpParActionPerformed

    private void jRadioButtonJeuxRechercherStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxRechercherStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButtonJeuxRechercherStateChanged

    private void jRadioButtonJeuxRechercherItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonJeuxRechercherItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED){
            jTextFieldRechercheJeux.setText("");
            ModelTableJeux myModel = new ModelTableJeux();
            TableRowSorter sorter = new TableRowSorter(myModel);
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*"));
            jTableJeux.setRowSorter(sorter);
        }
    }//GEN-LAST:event_jRadioButtonJeuxRechercherItemStateChanged
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Main().setVisible(true);        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAdherents;
    private javax.swing.ButtonGroup buttonGroupJeux;
    private javax.swing.JButton jButtonAdherent;
    private javax.swing.JButton jButtonAnimation;
    private javax.swing.JButton jButtonJeux;
    private javax.swing.JButton jButtonReservation;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonSortie;
    private javax.swing.JButton jButtonStatBilan;
    private javax.swing.JLabel jLabelLesJeuxDispo;
    private javax.swing.JLabel jLabelLesJeuxEmpPar;
    private javax.swing.JLabel jLabelLesJeuxSelect;
    private javax.swing.JLabel jLabelLesJeuxSortis;
    private javax.swing.JLabel jLabelTousAdh;
    private javax.swing.JLabel jLabelTousLesJeux;
    private javax.swing.JPanel jPanelAdherent;
    private javax.swing.JPanel jPanelJeux;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JRadioButton jRadioButtonAdherentAlertes;
    private javax.swing.JRadioButton jRadioButtonAdherentEmp;
    private javax.swing.JRadioButton jRadioButtonAdherentRech;
    private javax.swing.JRadioButton jRadioButtonAdherentTous;
    private javax.swing.JRadioButton jRadioButtonJeuxDispo;
    private javax.swing.JRadioButton jRadioButtonJeuxEmpPar;
    private javax.swing.JRadioButton jRadioButtonJeuxRechercher;
    private javax.swing.JRadioButton jRadioButtonJeuxSelect;
    private javax.swing.JRadioButton jRadioButtonJeuxSortis;
    private javax.swing.JRadioButton jRadioButtonJeuxTous;
    private javax.swing.JScrollPane jScrollPaneAdh;
    private javax.swing.JScrollPane jScrollPaneJeux;
    private javax.swing.JTable jTableAdherent;
    private javax.swing.JTable jTableJeux;
    private javax.swing.JTextField jTextFieldRechercheAdh;
    private javax.swing.JTextField jTextFieldRechercheJeux;
    // End of variables declaration//GEN-END:variables
}
