/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;

public class ReservationListeAdherent extends javax.swing.JFrame {

    public static ReservationListeAdherent reservation;

    /**
     * Creates new form Jeux
     */
    public ReservationListeAdherent(String refAdherent) {
        initComponents();
        Image icone = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("images/ludo.jpg"));
        this.setIconImage(icone);

    }

    /**
     * @param args the command line arguments
     */
    public static void reservationListeAdherent() {

        reservation.setVisible(true);
    }

    public static ReservationListeAdherent getInstance(String refAdherent) {

        if (reservation == null) {
            reservation = new ReservationListeAdherent(refAdherent);
        }
        reservationListeAdherent();
        return reservation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelresa = new javax.swing.JPanel();
        jScrollPanelReservation = new javax.swing.JScrollPane();
        jTableReservations = new javax.swing.JTable();
        jButtonAnnulerResa = new javax.swing.JButton();
        jButtonCreerResa = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jLabelAdherent = new javax.swing.JLabel();
        jTextFieldNomPrenomAdherent = new javax.swing.JTextField();
        jPanelMenu1 = new javax.swing.JPanel();
        jButtonSortie1 = new javax.swing.JButton();
        jButtonRetour1 = new javax.swing.JButton();
        jLabelTitre = new javax.swing.JLabel();

        setTitle("RESERVATION");
        setBackground(new java.awt.Color(199, 245, 233));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelresa.setBackground(new java.awt.Color(199, 245, 233));
        jPanelresa.setName(""); // NOI18N
        jPanelresa.setPreferredSize(new java.awt.Dimension(646, 825));

        jTableReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num", "Début", "Fin", "Sortie", "Retour", "Jeu", "Nom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableReservations.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableReservations.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableReservations.setRequestFocusEnabled(false);
        jTableReservations.getTableHeader().setReorderingAllowed(false);
        jScrollPanelReservation.setViewportView(jTableReservations);
        if (jTableReservations.getColumnModel().getColumnCount() > 0) {
            jTableReservations.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableReservations.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableReservations.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableReservations.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableReservations.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableReservations.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTableReservations.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        jButtonAnnulerResa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAnnulerResa.setText("Annuler résa"); // NOI18N
        jButtonAnnulerResa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerResaActionPerformed(evt);
            }
        });

        jButtonCreerResa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCreerResa.setText("Créer résa");
        jButtonCreerResa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerResaActionPerformed(evt);
            }
        });

        jButtonFermer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonFermer.setText("Fermer"); // NOI18N
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jLabelAdherent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAdherent.setText("Adhérent :");

        jTextFieldNomPrenomAdherent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNomPrenomAdherent.setEnabled(false);

        javax.swing.GroupLayout jPanelresaLayout = new javax.swing.GroupLayout(jPanelresa);
        jPanelresa.setLayout(jPanelresaLayout);
        jPanelresaLayout.setHorizontalGroup(
            jPanelresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelReservation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAnnulerResa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCreerResa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFermer)
                .addGap(42, 42, 42))
            .addGroup(jPanelresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNomPrenomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelresaLayout.setVerticalGroup(
            jPanelresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelresaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdherent)
                    .addComponent(jTextFieldNomPrenomAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnulerResa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreerResa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelMenu1.setBackground(new java.awt.Color(199, 245, 233));
        jPanelMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanelMenu1.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanelMenu1.setMinimumSize(new java.awt.Dimension(1280, 70));

        jButtonSortie1.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSortie1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSortie1.setText("SORTIE");
        jButtonSortie1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSortie1.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonSortie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortie1ActionPerformed(evt);
            }
        });

        jButtonRetour1.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRetour1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRetour1.setForeground(new java.awt.Color(255, 51, 51));
        jButtonRetour1.setText("RETOUR");
        jButtonRetour1.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonRetour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetour1ActionPerformed(evt);
            }
        });

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Réservations par adhérent");

        javax.swing.GroupLayout jPanelMenu1Layout = new javax.swing.GroupLayout(jPanelMenu1);
        jPanelMenu1.setLayout(jPanelMenu1Layout);
        jPanelMenu1Layout.setHorizontalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonSortie1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonRetour1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenu1Layout.setVerticalGroup(
            jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSortie1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButtonRetour1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelMenu1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, Short.MAX_VALUE)
            .addComponent(jPanelresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelresa, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        reservation.setVisible(false);
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jButtonAnnulerResaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerResaActionPerformed
        // TODO add your handling code here:
        ReservationAnnuler.getInstance();
    }//GEN-LAST:event_jButtonAnnulerResaActionPerformed

    private void jButtonCreerResaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerResaActionPerformed
        // TODO add your handling code here:
        // 1 Pour Création
        Reservation instance = Reservation.getInstance(1);
    }//GEN-LAST:event_jButtonCreerResaActionPerformed

    private void jButtonSortie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortie1ActionPerformed
        // TODO add your handling code here:
        // Il faudra appeler un constructeur avec un numéro de réservation
        // La sortie des jeux contenus dans la réservation se fera dans le programme SortieJeux
        JeuxChoix.getInstance("RESERVATION");
    }//GEN-LAST:event_jButtonSortie1ActionPerformed

    private void jButtonRetour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetour1ActionPerformed
        // TODO add your handling code here:
        //
         // Il faudra appeler un constructeur avec un numéro de réservation
        // Le retour des jeux contenus dans la réservation se fera dans le programme RetourJeux
      //  RetourJeux.getInstance();
    }//GEN-LAST:event_jButtonRetour1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulerResa;
    private javax.swing.JButton jButtonCreerResa;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonRetour1;
    private javax.swing.JButton jButtonSortie1;
    private javax.swing.JLabel jLabelAdherent;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelMenu1;
    private javax.swing.JPanel jPanelresa;
    private javax.swing.JScrollPane jScrollPanelReservation;
    private javax.swing.JTable jTableReservations;
    private javax.swing.JTextField jTextFieldNomPrenomAdherent;
    // End of variables declaration//GEN-END:variables
}
