/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 *
 */
public class ReservationAnnuler extends javax.swing.JFrame {

    public static Integer act;
    public static ReservationAnnuler reservation;

    /**
     * Creates new form Jeux
     */
    public ReservationAnnuler() {
        initComponents();
        Image icone = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("images/ludo.jpg"));
        this.setIconImage(icone);
    }

    /**
     * @param args the command line arguments
     */
    public static void reservationAnnuler() {
        reservation.setVisible(true);
    }

    public static ReservationAnnuler getInstance() {

        if (reservation == null) {
            reservation = new ReservationAnnuler();
        }
        reservationAnnuler();
        return reservation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRéservation = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelNumeroReservation = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jComboBoxReservation = new javax.swing.JComboBox();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelAnnulerReservation = new javax.swing.JLabel();

        setTitle("RESERVATION");
        setResizable(false);

        jPanelRéservation.setBackground(new java.awt.Color(199, 245, 233));
        jPanelRéservation.setName(""); // NOI18N
        jPanelRéservation.setPreferredSize(new java.awt.Dimension(646, 825));

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Réservation");

        jLabelNumeroReservation.setText("Numéro de réservation :");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jComboBoxReservation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReservationActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jLabelAnnulerReservation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAnnulerReservation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnnulerReservation.setText("Annuler une réservation");

        javax.swing.GroupLayout jPanelRéservationLayout = new javax.swing.GroupLayout(jPanelRéservation);
        jPanelRéservation.setLayout(jPanelRéservationLayout);
        jPanelRéservationLayout.setHorizontalGroup(
            jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRéservationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAnnuler)
                .addGap(18, 18, 18)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanelRéservationLayout.createSequentialGroup()
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRéservationLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelNumeroReservation)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBoxReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelAnnulerReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRéservationLayout.setVerticalGroup(
            jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRéservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAnnulerReservation)
                .addGap(43, 43, 43)
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroReservation)
                    .addComponent(jComboBoxReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRéservation, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRéservation, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        // Valider la création, ou la modification et quitter
        reservation.setVisible(false);
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jComboBoxReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReservationActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
// Quitter sans valider la création, ou la modification 
        reservation.setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxReservation;
    private javax.swing.JLabel jLabelAnnulerReservation;
    private javax.swing.JLabel jLabelNumeroReservation;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelRéservation;
    // End of variables declaration//GEN-END:variables
}
