/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 *
 */
public class ReservationRetirerJeu extends javax.swing.JFrame {
    
   
    public static ReservationRetirerJeu retirerjeu;

    /**
     * Creates new form Jeux
     */
    public ReservationRetirerJeu() {
        initComponents();
        Image icone = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("images/ludo.jpg"));
        this.setIconImage(icone);
    }

  
    public static void reservationRetirerJeu() {
        retirerjeu.setVisible(true);
    }
    
    public static ReservationRetirerJeu getInstance() {
        
        if (retirerjeu == null) {
            retirerjeu = new ReservationRetirerJeu();
        }
        reservationRetirerJeu();
        return retirerjeu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRéservation = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelNumeroReservation = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jComboBoxJeuxReserves = new javax.swing.JComboBox();
        jLabelRetirerJeu = new javax.swing.JLabel();
        jTextFieldNumReservation = new javax.swing.JTextField();
        jLabelJeuAretirer = new javax.swing.JLabel();
        jButtonAnnuler = new javax.swing.JButton();

        setTitle("RESERVATION");
        setResizable(false);

        jPanelRéservation.setBackground(new java.awt.Color(199, 245, 233));
        jPanelRéservation.setName(""); // NOI18N
        jPanelRéservation.setPreferredSize(new java.awt.Dimension(646, 825));

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Réservation");

        jLabelNumeroReservation.setText("Numéro de réservation :");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jComboBoxJeuxReserves.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJeuxReserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJeuxReservesActionPerformed(evt);
            }
        });

        jLabelRetirerJeu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRetirerJeu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRetirerJeu.setText("Retirer un jeu");

        jTextFieldNumReservation.setText("jTextField1");
        jTextFieldNumReservation.setEnabled(false);

        jLabelJeuAretirer.setText("Sélectionner le jeu à retirer de la réservation :");

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRéservationLayout = new javax.swing.GroupLayout(jPanelRéservation);
        jPanelRéservation.setLayout(jPanelRéservationLayout);
        jPanelRéservationLayout.setHorizontalGroup(
            jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRetirerJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelRéservationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRéservationLayout.createSequentialGroup()
                        .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelJeuAretirer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNumeroReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRéservationLayout.createSequentialGroup()
                        .addComponent(jButtonAnnuler)
                        .addGap(29, 29, 29)))
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJeuxReserves, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelRéservationLayout.setVerticalGroup(
            jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRéservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRetirerJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroReservation)
                    .addComponent(jTextFieldNumReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJeuxReserves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJeuAretirer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanelRéservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRéservation, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRéservation, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
     
        // Valider la création, ou la modification et quitter
        // 
        retirerjeu.setVisible(false);
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jComboBoxJeuxReservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJeuxReservesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJeuxReservesActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
           // Quitter sans valider la création, ou la modification 
        // 
        
        retirerjeu.setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxJeuxReserves;
    private javax.swing.JLabel jLabelJeuAretirer;
    private javax.swing.JLabel jLabelNumeroReservation;
    private javax.swing.JLabel jLabelRetirerJeu;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelRéservation;
    private javax.swing.JTextField jTextFieldNumReservation;
    // End of variables declaration//GEN-END:variables
}
