/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.ArrayList;
import javax.swing.JFrame;
import org.jdesktop.swingx.calendar.*;

/**
 *
 * @author andre
 */
public class RetourJeux extends javax.swing.JFrame {
    
    private static  RetourJeux instance = null;

    /**
     * Creates new form Sortie
     */
    public RetourJeux() {
        initComponents();
        this.setLocation(400, 50);
        setVisible(true);
        CalendarUtils cal = new CalendarUtils();       
    }


    public static RetourJeux getInstance(JFrame mere) {
        frame = mere;
        if (instance == null) {
            instance = new RetourJeux();
        }
        instance.setVisible(true);
        return instance;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRetour = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelListeDesJeux = new javax.swing.JLabel();
        jScrollPaneListeJeux = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonRetourAutreJeux = new javax.swing.JButton();
        jLabelLabelAdhérent = new javax.swing.JLabel();
        jLabelAdherent = new javax.swing.JLabel();
        jButtonChoixAdherent = new javax.swing.JButton();
        jLabelNotes = new javax.swing.JLabel();
        jScrollPaneNotes = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jButtonEffacerNotes = new javax.swing.JButton();
        jXDatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        jLabelDate = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();

        setTitle("SORTIE D'UN OU PLUSIEURS JEUX");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelRetour.setBackground(new java.awt.Color(199, 245, 233));

        jButtonOK.setText("OK");

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jLabelListeDesJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelListeDesJeux.setText("Liste de jeux empruntés : ");

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPaneListeJeux.setViewportView(jList1);

        jButtonRetourAutreJeux.setText("Choisir un jeu");
        jButtonRetourAutreJeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourAutreJeuxActionPerformed(evt);
            }
        });

        jLabelLabelAdhérent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLabelAdhérent.setText("Adhérent :");

        jLabelAdherent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAdherent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonChoixAdherent.setText("Choisir l'adhérent");
        jButtonChoixAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoixAdherentActionPerformed(evt);
            }
        });

        jLabelNotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNotes.setText("Notes :");

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setRows(5);
        jScrollPaneNotes.setViewportView(jTextAreaNotes);

        jButtonEffacerNotes.setText("Effacer les notes");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDate.setText("Date :");

        jButtonRetour.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRetour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRetour.setForeground(new java.awt.Color(255, 51, 51));
        jButtonRetour.setText("RETOUR");
        jButtonRetour.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRetourLayout = new javax.swing.GroupLayout(jPanelRetour);
        jPanelRetour.setLayout(jPanelRetourLayout);
        jPanelRetourLayout.setHorizontalGroup(
            jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRetourLayout.createSequentialGroup()
                .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRetourLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonAnnuler))
                    .addGroup(jPanelRetourLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXDatePickerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelRetourLayout.createSequentialGroup()
                                    .addComponent(jLabelNotes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEffacerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRetourLayout.createSequentialGroup()
                                    .addComponent(jLabelListeDesJeux)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                    .addComponent(jButtonRetourAutreJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPaneListeJeux)
                                .addGroup(jPanelRetourLayout.createSequentialGroup()
                                    .addComponent(jLabelLabelAdhérent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonChoixAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPaneNotes))
                            .addComponent(jLabelDate)
                            .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelRetourLayout.setVerticalGroup(
            jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRetourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelListeDesJeux)
                    .addComponent(jButtonRetourAutreJeux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListeJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelAdhérent)
                    .addComponent(jButtonChoixAdherent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNotes)
                    .addComponent(jButtonEffacerNotes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePickerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelRetourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonAnnuler))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonRetourAutreJeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourAutreJeuxActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        JeuChoix.getInstance(frame , 0 , null , null);
    }//GEN-LAST:event_jButtonRetourAutreJeuxActionPerformed

    private void jButtonChoixAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoixAdherentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdherentChoix.choix();
    }//GEN-LAST:event_jButtonChoixAdherentActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    private static JFrame frame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonChoixAdherent;
    private javax.swing.JButton jButtonEffacerNotes;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonRetourAutreJeux;
    private javax.swing.JLabel jLabelAdherent;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelLabelAdhérent;
    private javax.swing.JLabel jLabelListeDesJeux;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanelRetour;
    private javax.swing.JScrollPane jScrollPaneListeJeux;
    private javax.swing.JScrollPane jScrollPaneNotes;
    private javax.swing.JTextArea jTextAreaNotes;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerDate;
    // End of variables declaration//GEN-END:variables
}
