/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.*;
import org.jdesktop.swingx.calendar.*;

/**
 *
 * @author andre
 */
public class SortieChoix extends javax.swing.JFrame {
    
    private static SortieChoix instance = null;
    
    /**
     * Creates new form Sortie
     */
    public SortieChoix() {
        initComponents();
        this.setLocation(400, 50);
        CalendarUtils cal = new CalendarUtils();
        
    }

    public static SortieChoix getInstance(JFrame mere , ArrayList list,String libAdherent) {
        frame = mere;
        liste = list;
        libAdh = libAdherent;
        if (instance == null) {
            instance = new SortieChoix();
        }
        instance.setVisible(true);
        if (list != null){
            instance.jListListeJeuxSelect.setListData(list.toArray());
        }
        instance.jLabelAdherent.setText(libAdherent);
        instance.jXDatePickerDate.setDate(new java.util.Date());
        frame.setEnabled(false);
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSortie = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonSortie = new javax.swing.JButton();
        jLabelListeDesJeux = new javax.swing.JLabel();
        jScrollPaneListeJeux = new javax.swing.JScrollPane();
        jListListeJeuxSelect = new javax.swing.JList();
        jButtonSortirAutreJeux = new javax.swing.JButton();
        jLabelLabelAdhérent = new javax.swing.JLabel();
        jLabelAdherent = new javax.swing.JLabel();
        jButtonChoixAdh = new javax.swing.JButton();
        jLabelNotes = new javax.swing.JLabel();
        jScrollPaneNotes = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonEffacerNotes = new javax.swing.JButton();
        jXDatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        jLabelDate = new javax.swing.JLabel();

        setTitle("SORTIE D'UN OU PLUSIEURS JEUX");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelSortie.setBackground(new java.awt.Color(199, 245, 233));

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jButtonSortie.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSortie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSortie.setText("SORTIE");
        jButtonSortie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSortie.setEnabled(false);
        jButtonSortie.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabelListeDesJeux.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelListeDesJeux.setText("Liste de jeux empruntés : ");

        jScrollPaneListeJeux.setViewportView(jListListeJeuxSelect);

        jButtonSortirAutreJeux.setText("Sortir un autre jeu");
        jButtonSortirAutreJeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortirAutreJeuxActionPerformed(evt);
            }
        });

        jLabelLabelAdhérent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLabelAdhérent.setText("Adhérent :");

        jLabelAdherent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAdherent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonChoixAdh.setText("Choisir l'adhérent");
        jButtonChoixAdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoixAdhActionPerformed(evt);
            }
        });

        jLabelNotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNotes.setText("Notes :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneNotes.setViewportView(jTextArea1);

        jButtonEffacerNotes.setText("Effacer les notes");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDate.setText("Date :");

        javax.swing.GroupLayout jPanelSortieLayout = new javax.swing.GroupLayout(jPanelSortie);
        jPanelSortie.setLayout(jPanelSortieLayout);
        jPanelSortieLayout.setHorizontalGroup(
            jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSortieLayout.createSequentialGroup()
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSortieLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonAnnuler))
                    .addGroup(jPanelSortieLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXDatePickerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelSortieLayout.createSequentialGroup()
                                    .addComponent(jLabelNotes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEffacerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelSortieLayout.createSequentialGroup()
                                    .addComponent(jLabelListeDesJeux)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                    .addComponent(jButtonSortirAutreJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelSortieLayout.createSequentialGroup()
                                    .addComponent(jLabelLabelAdhérent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonChoixAdh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPaneListeJeux)
                                .addComponent(jScrollPaneNotes)
                                .addComponent(jLabelAdherent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelDate))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelSortieLayout.setVerticalGroup(
            jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSortieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelListeDesJeux)
                    .addComponent(jButtonSortirAutreJeux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListeJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabelAdhérent)
                    .addComponent(jButtonChoixAdh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNotes)
                    .addComponent(jButtonEffacerNotes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePickerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonAnnuler))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSortie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        setVisible(false);   
        frame.setEnabled(true);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonSortirAutreJeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortirAutreJeuxActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        JeuChoix.getInstance(frame,2,liste,libAdh);
    }//GEN-LAST:event_jButtonSortirAutreJeuxActionPerformed

    private void jButtonChoixAdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoixAdhActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdherentChoix.choix();
    }//GEN-LAST:event_jButtonChoixAdhActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        //valider la sortie
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */


    private static JFrame frame;
    private static ArrayList liste;
    private static String libAdh;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonChoixAdh;
    private javax.swing.JButton jButtonEffacerNotes;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSortie;
    private javax.swing.JButton jButtonSortirAutreJeux;
    private javax.swing.JLabel jLabelAdherent;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelLabelAdhérent;
    private javax.swing.JLabel jLabelListeDesJeux;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JList jListListeJeuxSelect;
    private javax.swing.JPanel jPanelSortie;
    private javax.swing.JScrollPane jScrollPaneListeJeux;
    private javax.swing.JScrollPane jScrollPaneNotes;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerDate;
    // End of variables declaration//GEN-END:variables
}
